//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIN_HSCB_QuaTrinhNghienCuu_01
    {
        public Nullable<int> MaCanBoId { get; set; }
        public string MaSo { get; set; }
        public string NamBatDau { get; set; }
        public string NamKetThuc { get; set; }
        public Nullable<double> KinhPhi { get; set; }
        public string NgayNghiemThu { get; set; }
        public string KetQua { get; set; }
        public string ThoiGian { get; set; }
        public string LaChuNhiemText { get; set; }
        public string TenDeTai { get; set; }
        public string ThamGiaText { get; set; }
    }
}
