//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIN_HSCB_LyLichCanBo_01
    {
        public string Ten { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string Code { get; set; }
        public Nullable<int> MaTruongId { get; set; }
        public Nullable<int> MaKhoaId { get; set; }
        public Nullable<int> MaBoMonId { get; set; }
        public Nullable<int> PhongThiNghiemId { get; set; }
        public Nullable<int> ChucVu { get; set; }
        public Nullable<int> HocVi { get; set; }
        public Nullable<int> NamDatHocVi { get; set; }
        public Nullable<int> HocHam { get; set; }
        public Nullable<int> NamDatHocHam { get; set; }
        public string DiaChiCQ { get; set; }
        public string DienThoaiCQ { get; set; }
        public string FaxCQ { get; set; }
        public string EmailCQ { get; set; }
        public string DiaChiCN { get; set; }
        public string DienThoaiCN { get; set; }
        public string FaxCN { get; set; }
        public string EmailCN { get; set; }
        public string WebSiteCN { get; set; }
        public string HinhAnh { get; set; }
        public string TenTruongVien { get; set; }
        public string TenBoMon { get; set; }
        public string TenChucVu { get; set; }
        public string TenPTN { get; set; }
        public string TenKhoa { get; set; }
        public int Id { get; set; }
        public string TenHocHam { get; set; }
        public string TenHocVi { get; set; }
    }
}
