//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIN_HSCB_XuatBanSach_TrongNuoc
    {
        public int MaCanBoId { get; set; }
        public string TenSach { get; set; }
        public Nullable<int> NhaXuatBan { get; set; }
        public Nullable<int> NamXuatBan { get; set; }
        public Nullable<bool> TacGiaChinh { get; set; }
        public Nullable<bool> DongTacGia { get; set; }
        public string ButDanh { get; set; }
        public string TacGiaChinhText { get; set; }
        public string DongTacGiaText { get; set; }
        public string NXB { get; set; }
        public Nullable<int> SanPham { get; set; }
    }
}
