//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIN_HSCB_TrinhDoNgoaiNgu
    {
        public string NgoaiNgu { get; set; }
        public Nullable<int> Nghe { get; set; }
        public Nullable<int> Noi { get; set; }
        public Nullable<int> Viet { get; set; }
        public Nullable<int> Doc { get; set; }
        public Nullable<int> MaCanBoId { get; set; }
        public string NgheTot { get; set; }
        public string NgheKha { get; set; }
        public string NgheTB { get; set; }
        public string NoiTot { get; set; }
        public string NoiKha { get; set; }
        public string NoiTB { get; set; }
        public string VietTot { get; set; }
        public string VietKha { get; set; }
        public string VietTB { get; set; }
        public string DocTot { get; set; }
        public string DocKha { get; set; }
        public string DocTB { get; set; }
        public Nullable<int> NgoaiNguId { get; set; }
    }
}
