//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dhu_DA_ThongTinChung
    {
        public string TenDA { get; set; }
        public string LoaiDA { get; set; }
        public string LinhVuc { get; set; }
        public string ChuNhiem { get; set; }
        public int MaDA { get; set; }
        public string ThoiGianBatDau { get; set; }
        public string ThoiGianKetThuc { get; set; }
        public string ChuTri { get; set; }
        public string MucTieu { get; set; }
        public string NoiDung { get; set; }
        public string SanPham { get; set; }
        public Nullable<int> LoaiDuanId { get; set; }
        public string ChuongTrinh { get; set; }
        public Nullable<int> ThuocChuongTrinhId { get; set; }
        public Nullable<int> ThuocLinhVucId { get; set; }
        public Nullable<int> ChuNhiemId { get; set; }
        public string MaSo { get; set; }
        public Nullable<int> CoQuanChuTri { get; set; }
        public string TinhTrangThucHien { get; set; }
    }
}
