//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dhu_PTN_DeTaiDuAn
    {
        public int PTNId { get; set; }
        public string ThoiGian { get; set; }
        public string KetQuaNghiemThu { get; set; }
        public string KetQuaChinh { get; set; }
        public string GhiChu { get; set; }
        public string ThoiGianThucHien { get; set; }
        public Nullable<double> KinhPhi { get; set; }
        public string CapMaSo { get; set; }
        public string TenDeTai { get; set; }
    }
}
