//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dhu_PTN_ThongTinChung
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Fax { get; set; }
        public Nullable<int> ThietBiId { get; set; }
        public string ThietBiTen { get; set; }
        public string TenCQCQ { get; set; }
        public string NameNonUnicode { get; set; }
        public Nullable<int> PhanLoaiId { get; set; }
        public Nullable<int> PhanCapId { get; set; }
        public Nullable<int> TruongPhongId { get; set; }
        public Nullable<int> TruongVienId { get; set; }
        public string LinhVucName { get; set; }
    }
}
