//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dhu_PTN_PLAN_USEDYN_TuyenDung
    {
        public string HocVi { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public int YearId { get; set; }
    }
}
