//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dhu_PTN_PhanBoNhanLuc
    {
        public Nullable<int> PTNId { get; set; }
        public string ChucVu { get; set; }
        public string HocVi { get; set; }
        public string TenCanBo { get; set; }
        public Nullable<bool> CanBoCoHuu { get; set; }
        public string EmailCN { get; set; }
        public string ChuyenNganh { get; set; }
    }
}
