//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dhu_NhomNghienCuuManh
    {
        public string PTN { get; set; }
        public int Id { get; set; }
        public string LanhVucChinh { get; set; }
        public string TruongNhom { get; set; }
        public string DonVi { get; set; }
        public Nullable<int> CtId { get; set; }
    }
}
