//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dhu_PTN_ThietBiChinh
    {
        public string Ten { get; set; }
        public string ThongSoKyThuat { get; set; }
        public string CongDung { get; set; }
        public Nullable<double> TriGia { get; set; }
        public string NamMua { get; set; }
        public string TanSuat { get; set; }
        public int PTNId { get; set; }
    }
}
