//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_DM_BuocThucHien_ChiTiet00_BuocId
    {
        public int Id { get; set; }
        public string Ten { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> BuocId { get; set; }
        public string tbl_DM_BuocThucHien_BuocId_Ten { get; set; }
    }
}
