//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_HOINGHI_BuocThucHien00_HoiNghiId
    {
        public int Id { get; set; }
        public int HoiNghiId { get; set; }
        public string Buocthuchien { get; set; }
        public Nullable<System.DateTime> Thoigianbatdau { get; set; }
        public Nullable<System.DateTime> Thoigianketthuc { get; set; }
        public string Noidung { get; set; }
        public string Trangthaithuchien { get; set; }
        public string Ketquathuchien { get; set; }
        public string Ghichu { get; set; }
        public string Nguoichutri { get; set; }
        public string HinhAnhFile { get; set; }
        public string tbl_HOINGHI_DS_HN_HT_HoiNghiId_Name { get; set; }
    }
}
