//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_DA_ThongTinChung02_ChuNhiemId
    {
        public int Id { get; set; }
        public string Ten { get; set; }
        public string MaSo { get; set; }
        public Nullable<int> LoaiDuanId { get; set; }
        public Nullable<int> ThuocChuongTrinhId { get; set; }
        public Nullable<int> ThuocLinhVucId { get; set; }
        public Nullable<int> ChuNhiemId { get; set; }
        public Nullable<int> DongChuNhiemId { get; set; }
        public string ThoiGianBatDau { get; set; }
        public string ThoiGianKetThuc { get; set; }
        public string SoThang { get; set; }
        public Nullable<double> KinhPhi { get; set; }
        public Nullable<double> KinhPhiSuNghiepKH { get; set; }
        public Nullable<int> CoQuanCapKinhPhi { get; set; }
        public Nullable<int> CoQuanChuQuan { get; set; }
        public Nullable<int> CoQuanChuTri { get; set; }
        public string DiaChiUngDung { get; set; }
        public string MucTieu { get; set; }
        public string NoiDung { get; set; }
        public string SanPham { get; set; }
        public string TomTatKetQua { get; set; }
        public string tbl_DM_LoaiDuAn_LoaiDuanId_Ten { get; set; }
        public string tbl_DM_LinhVuc_ThuocLinhVucId_Ten { get; set; }
        public string tbl_HSCB_LyLichCanBo_ChuNhiemId_Ten { get; set; }
    }
}
