//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_HSCB_BaiBao
    {
        public int Id { get; set; }
        public Nullable<int> Yearth { get; set; }
        public Nullable<int> MagazineId { get; set; }
        public string MagazineDetail { get; set; }
        public string Abstract { get; set; }
        public string PaperTitle { get; set; }
        public string GroupAuthor { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public Nullable<int> TypeOfAuthor { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<int> ProgrameId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string AttachFile { get; set; }
        public Nullable<int> Months { get; set; }
        public string WebLink { get; set; }
    }
}
