//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_PTN_WORKING_CongTrinhKHCN
    {
        public int Id { get; set; }
        public Nullable<int> MaPTNId { get; set; }
        public Nullable<int> PaperId { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
    }
}
