//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_DA_BUOCTH_PhieuDangKyKetQua01_DuAnId
    {
        public int Id { get; set; }
        public Nullable<int> BuocTHId { get; set; }
        public string Ten { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh_File { get; set; }
        public Nullable<int> DuAnId { get; set; }
        public string tbl_DM_BuocThucHien_ChiTiet_BuocTHId_Ten { get; set; }
        public string tbl_DA_ThongTinChung_DuAnId_Ten { get; set; }
    }
}
