//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_DA_SanPhamDeTai00_DuAnId
    {
        public int Id { get; set; }
        public Nullable<int> DuAnId { get; set; }
        public Nullable<double> TS { get; set; }
        public Nullable<double> ThS { get; set; }
        public Nullable<double> DH { get; set; }
        public Nullable<double> Khac { get; set; }
        public Nullable<double> BaiBaoTN { get; set; }
        public Nullable<double> BaiBaoQT { get; set; }
        public Nullable<double> KyYeuTN { get; set; }
        public Nullable<double> KyYeuQT { get; set; }
        public Nullable<bool> LoaiDeTaiOrDuAn { get; set; }
        public string tbl_DA_ThongTinChung_DuAnId_Ten { get; set; }
        public Nullable<int> Nam { get; set; }
    }
}
