//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_PTN_DichVu01_DichVuId
    {
        public int Id { get; set; }
        public Nullable<int> PhongTNId { get; set; }
        public Nullable<int> DichVuId { get; set; }
        public Nullable<int> SoMau { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> DoanhSo { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string tbl_PTN_ThongTinChung_PhongTNId_Name { get; set; }
        public string tbl_DM_DichVu_DichVuId_Ten { get; set; }
    }
}
