//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_PTN_PLAN_DeXuatCapTrangThietBi01_TrangThietBiId
    {
        public int Id { get; set; }
        public Nullable<int> KeHoachId { get; set; }
        public Nullable<int> TrangThietBiId { get; set; }
        public Nullable<double> KinhPhi { get; set; }
        public string GhiChu { get; set; }
        public string tbl_PTN_PLAN_LapKeHoachHoatDong_KeHoachId_Ten { get; set; }
        public Nullable<int> tbl_PTN_INFO_TrangThietBi_TrangThietBiId_Id { get; set; }
    }
}
