//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_HOINGHI_DS_KhachMoi02_HocViId
    {
        public int Id { get; set; }
        public Nullable<int> HoiNghiId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> LinhVucId { get; set; }
        public Nullable<int> HocViId { get; set; }
        public Nullable<int> TruongVienId { get; set; }
        public Nullable<int> ChucvuId { get; set; }
        public string Mobile { get; set; }
        public string DTNha { get; set; }
        public Nullable<bool> BaiBaoCao { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<int> DiaDiemId { get; set; }
        public string tbl_HOINGHI_DS_HN_HT_HoiNghiId_Name { get; set; }
        public string tbl_HOINGHI_LinhVuc_LinhVucId_Name { get; set; }
        public string tbl_DM_HocVi_HocViId_Ten { get; set; }
    }
}
