//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_DA_QuaTrinhThucHien_File00_MaBuocDuAnId
    {
        public int Id { get; set; }
        public Nullable<int> MaBuocDuAnId { get; set; }
        public string HinhAnh_File { get; set; }
        public Nullable<int> tbl_DA_QuaTrinhThucHien_MaBuocDuAnId_Id { get; set; }
    }
}
