//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_BB_Science_Magazine_GroupAuthor00_Science_MagazineId
    {
        public int Id { get; set; }
        public Nullable<int> Science_MagazineId { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string tbl_BB_Science_Magazine2_Science_MagazineId_MagazineDetail { get; set; }
    }
}
