//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_DM_BoMon00_MaKhoaId
    {
        public int Id { get; set; }
        public string Ten { get; set; }
        public Nullable<int> MaKhoaId { get; set; }
        public string tbl_DM_KhoaPhongBan_MaKhoaId_Ten { get; set; }
    }
}
