//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_TH_DM_PhanBien03_CanBo3Id
    {
        public int Id { get; set; }
        public Nullable<int> SinhVienId { get; set; }
        public Nullable<int> CanBo1Id { get; set; }
        public Nullable<double> Diem1 { get; set; }
        public Nullable<int> CanBo2Id { get; set; }
        public Nullable<double> Diem2 { get; set; }
        public Nullable<int> CanBo3Id { get; set; }
        public Nullable<double> Diem3 { get; set; }
        public Nullable<double> TrungBinh { get; set; }
        public string XepHang { get; set; }
        public string tbl_GIAITHUONG_SV_SinhVien_SinhVienId_Name { get; set; }
        public string tbl_HSCB_LyLichCanBo_CanBo1Id_Ten { get; set; }
        public string tbl_HSCB_LyLichCanBo_CanBo2Id_Ten { get; set; }
        public string tbl_HSCB_LyLichCanBo_CanBo3Id_Ten { get; set; }
    }
}
