//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_KP_NguonVon
    {
        public int Id { get; set; }
        public Nullable<int> NguonVonId { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<int> ThuMucId { get; set; }
    }
}
