//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_TH_CongVanDi00_LoaiCongVan
    {
        public int Id { get; set; }
        public System.DateTime NgayGui { get; set; }
        public string NguoiKy { get; set; }
        public Nullable<int> LoaiCongVan { get; set; }
        public string SoPhatHanh { get; set; }
        public string TenCongVan { get; set; }
        public string SoCongVan { get; set; }
        public string TrichYeu { get; set; }
        public string DienGiai { get; set; }
        public System.DateTime NgayPhatHanh { get; set; }
        public Nullable<int> NoiPhatHanhId { get; set; }
        public Nullable<int> CoQuanNhanId { get; set; }
        public string HinhAnh { get; set; }
        public string ChuyenVien { get; set; }
        public string GhiChu { get; set; }
        public string tbl_TH_DM_LoaiCongVan_LoaiCongVan_Name { get; set; }
    }
}
