//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_PTN_WORKING_HoatDongSoHuuTriTue01_SangCheId
    {
        public int Id { get; set; }
        public int PhongTNId { get; set; }
        public Nullable<int> SangCheId { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string SoBangDocQuyen { get; set; }
        public string HoSoKemTheo { get; set; }
        public string TomTat { get; set; }
        public string tbl_PTN_INFO_ThongTinChung_PhongTNId_Name { get; set; }
        public string tbl_SHTT_Thongtinchung_SangCheId_Name { get; set; }
    }
}
