//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_HSCB_BaiBao00_AuthorId
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Yearth { get; set; }
        public string Magazine { get; set; }
        public string MagazineDetail { get; set; }
        public string PaperTitle { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string SanPham { get; set; }
        public string ISSN { get; set; }
        public Nullable<double> DiemIF { get; set; }
        public Nullable<bool> TapChiTrongNuoc { get; set; }
        public Nullable<bool> TapChiQT { get; set; }
        public string tbl_HSCB_LyLichCanBo_AuthorId_Ten { get; set; }
    }
}
