//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_PTN_TinhHinhHoatDong
    {
        public int Id { get; set; }
        public int MaPTNId { get; set; }
        public Nullable<double> TanSuatSuDung { get; set; }
        public string HoatDongSoHuuTriTue { get; set; }
    }
}
