//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_PTN_DuKienThucHienDuAn02_DeTaiId
    {
        public int Id { get; set; }
        public Nullable<int> PhongTNId { get; set; }
        public string ThoiGianDuKien { get; set; }
        public Nullable<int> LoaiDuAn { get; set; }
        public Nullable<int> DeTaiId { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string ThoiGian { get; set; }
        public Nullable<double> KinhPhi { get; set; }
        public string TapChiQT { get; set; }
        public string TapChiTN { get; set; }
        public string Patent { get; set; }
        public string SoTS_ThS { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string tbl_PTN_ThongTinChung_PhongTNId_Name { get; set; }
        public string tbl_DM_LoaiDuAn_LoaiDuAn_Ten { get; set; }
        public string tbl_DA_ThongTinChung_DeTaiId_Ten { get; set; }
    }
}
