//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_PTN_TuyenDung02_HocViId
    {
        public int Id { get; set; }
        public Nullable<int> PhongTNId { get; set; }
        public Nullable<int> MaNguonNhanLucId { get; set; }
        public string ThoiGian { get; set; }
        public Nullable<int> HocViId { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string KinhPhi { get; set; }
        public string GhiChu { get; set; }
        public string tbl_PTN_ThongTinChung_PhongTNId_Name { get; set; }
        public string tbl_DM_DaoTaoNhanLuc_MaNguonNhanLucId_Name { get; set; }
        public string tbl_DM_HocVi_HocViId_Ten { get; set; }
    }
}
