//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_HSCB_ThamGiaChuongTrinh00_MaCanBo
    {
        public int Id { get; set; }
        public Nullable<int> MaCanBo { get; set; }
        public string ThoiGianBatDau { get; set; }
        public string ThoiGianKetThuc { get; set; }
        public string ChucDanh { get; set; }
        public string TenChuongTrinh { get; set; }
        public string tbl_HSCB_LyLichCanBo_MaCanBo_Ten { get; set; }
    }
}
