//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_SHTT_ChuyenGiaoQuyen01_LoaiVanBangId
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> VanBangId { get; set; }
        public Nullable<int> LoaiVanBangId { get; set; }
        public string NguoiChuyen { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<double> KinhPhi { get; set; }
        public string HieuQua { get; set; }
        public string NguoiNhan { get; set; }
        public string DiaChi { get; set; }
        public string tbl_SHTT_VanBangBaoHo_VanBangId_Name { get; set; }
        public string tbl_SHTT_LoaiVanBang_LoaiVanBangId_Name { get; set; }
    }
}
