//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_HOINGHI_Diadiem
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Adrsess { get; set; }
        public string Mobile { get; set; }
        public string DTCoquan { get; set; }
        public string Email { get; set; }
        public string NguoiDaiDien { get; set; }
        public string Website { get; set; }
        public string MoTa { get; set; }
        public string GhiChu { get; set; }
    }
}
