//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_PTN_ThongTinChung02_DoiTuongPhucVu
    {
        public int Id { get; set; }
        public string Ten { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Fax { get; set; }
        public Nullable<int> TruongPhong { get; set; }
        public Nullable<int> CoQuan { get; set; }
        public string LanVucHoatDong { get; set; }
        public string MucTieuHoatDong { get; set; }
        public Nullable<int> DoiTuongPhucVu { get; set; }
        public Nullable<int> NamTrienKhai { get; set; }
        public string KetQuaDatDuoc { get; set; }
        public Nullable<double> TongVon { get; set; }
        public Nullable<double> TongGiaTriThietBi { get; set; }
        public Nullable<double> TongDienTich { get; set; }
        public string PTNChuyenSau { get; set; }
        public string tbl_HSCB_LyLichCanBo_TruongPhong_Ten { get; set; }
        public string tbl_DM_TruongVien_CoQuan_Ten { get; set; }
        public string tbl_DM_DoiTuongPhucVu_DoiTuongPhucVu_Ten { get; set; }
    }
}
