//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_SHTT_VanBangBaoHo00_TenSangCheId
    {
        public int Id { get; set; }
        public string SoBang { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string SoDon { get; set; }
        public string CongBoBang { get; set; }
        public string DaiDienSHTT { get; set; }
        public Nullable<int> TenSangCheId { get; set; }
        public string TomTat { get; set; }
        public string IPC { get; set; }
        public Nullable<System.DateTime> NgayNopDon { get; set; }
        public string CongBoDon { get; set; }
        public string tbl_SHTT_SangChe_TenSangCheId_Name { get; set; }
    }
}
