//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_PTN_PLAN_ThucHienDeTai01_DonViTinh
    {
        public int Id { get; set; }
        public Nullable<int> KeHoachId { get; set; }
        public Nullable<int> TenDeTai { get; set; }
        public Nullable<double> ThoiGianThuHien { get; set; }
        public Nullable<int> DonViTinh { get; set; }
        public Nullable<double> KinhPhi { get; set; }
        public string KetQuaDK { get; set; }
        public string tbl_PTN_PLAN_LapKeHoachHoatDong_KeHoachId_Ten { get; set; }
        public string tbl_PTN_DM_DonVi_ThoiGian_DonViTinh_Ten { get; set; }
    }
}
