//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_SHTT_NhanHieu00_VanBangId
    {
        public int Id { get; set; }
        public Nullable<int> VanBangId { get; set; }
        public string SoDon { get; set; }
        public Nullable<System.DateTime> NgayNopDon { get; set; }
        public Nullable<System.DateTime> NgayUuTien { get; set; }
        public string TenNhanHieu { get; set; }
        public string HinhAnh { get; set; }
        public string LoaiNhanHieu { get; set; }
        public string MauNhanHieu { get; set; }
        public string NhomSP { get; set; }
        public string NguoiNopDon1 { get; set; }
        public string DiaChi { get; set; }
        public string ToChucDaiDien { get; set; }
        public string TaiLieuTrungGian { get; set; }
        public string tbl_SHTT_VanBangBaoHo_VanBangId_Name { get; set; }
    }
}
