//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_HSCB_LyLichCanBo03_PhongThiNghiemId
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Ten { get; set; }
        public string NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<int> MaTruongId { get; set; }
        public Nullable<int> MaKhoaId { get; set; }
        public Nullable<int> MaBoMonId { get; set; }
        public Nullable<int> PhongThiNghiemId { get; set; }
        public Nullable<int> ChucVu { get; set; }
        public Nullable<int> HocVi { get; set; }
        public Nullable<int> NamDatHocVi { get; set; }
        public Nullable<int> HocHam { get; set; }
        public Nullable<int> NamDatHocHam { get; set; }
        public string DiaChiCQ { get; set; }
        public string DienThoaiCQ { get; set; }
        public string FaxCQ { get; set; }
        public string EmailCQ { get; set; }
        public string DiaChiCN { get; set; }
        public string DienThoaiCN { get; set; }
        public string FaxCN { get; set; }
        public string EmailCN { get; set; }
        public string WebSiteCN { get; set; }
        public string HinhAnh { get; set; }
        public string NameNoneUnicode { get; set; }
        public Nullable<bool> isScience { get; set; }
        public string tbl_DM_TruongVien_MaTruongId_Ten { get; set; }
        public string tbl_DM_KhoaPhongBan_MaKhoaId_Ten { get; set; }
        public string tbl_DM_BoMon_MaBoMonId_Ten { get; set; }
        public string tbl_PTN_INFO_ThongTinChung_PhongThiNghiemId_Name { get; set; }
    }
}
