//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_gc_tbl_BB_Science_Magazine203_TypeOfAuthor
    {
        public int Id { get; set; }
        public string PaperTitle { get; set; }
        public Nullable<int> Yearth { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> ProgrameId { get; set; }
        public string Magazine { get; set; }
        public Nullable<int> MagazineId { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string MagazineDetail { get; set; }
        public string Abstract { get; set; }
        public Nullable<int> TypeOfAuthor { get; set; }
        public string HinhAnh_File { get; set; }
        public Nullable<int> Months { get; set; }
        public string ProjectCode { get; set; }
        public string WebLink { get; set; }
        public string NhomTacGia { get; set; }
        public Nullable<int> LoaiTapChiId { get; set; }
        public Nullable<int> LinhVucId { get; set; }
        public string tbl_DM_LoaiTapChi_Ten { get; set; }
        public string tbl_BB_Magazine_MagazineId_Name { get; set; }
        public string tbl_BB_Science_AuthorId_Name { get; set; }
        public string tbl_DM_LoaiTacGia_TypeOfAuthor_Ten { get; set; }
    }
}
