//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_CJVINA_ThucTe
    {
        public int Id { get; set; }
        public Nullable<int> FormularId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> WorkingNoteId { get; set; }
        public int tbl_CJVINA_WorkingNote_Detail_WorkingNoteId_Id { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Error { get; set; }
    }
}
