//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_HOINGHI_ChiPhi
    {
        public int Id { get; set; }
        public Nullable<int> HoinghiId { get; set; }
        public string tbl_HOINGHI_DS_HN_HT_HoinghiId_Name { get; set; }
        public string Noidungchi { get; set; }
        public string Thoigian { get; set; }
        public string Nguoichi { get; set; }
        public Nullable<double> Sotien { get; set; }
        public string Nguoinhantien { get; set; }
    }
}
