//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_BB_Science_Magazine
    {
        public int Id { get; set; }
        public string PaperTitle { get; set; }
        public Nullable<int> Yearth { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> ProgrameId { get; set; }
        public string Magazine { get; set; }
        public Nullable<int> MagazineId { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string MagazineDetail { get; set; }
        public string Abstract { get; set; }
        public Nullable<int> TypeOfAuthor { get; set; }
        public string AttachFile { get; set; }
        public Nullable<int> Month { get; set; }
        public string GroupAuthor { get; set; }
        public string ProjectCode { get; set; }
        public string WebLink { get; set; }
        public int tbl_BB_UnitId { get; set; }
        public string tbl_BB_UnitName { get; set; }
        public string tbl_BB_UnitCode { get; set; }
        public int tbl_BB_ProgrameId { get; set; }
        public string tbl_BB_ProgrameName { get; set; }
        public string tbl_BB_ProgrameCode { get; set; }
        public string tbl_BB_ProgrameNote { get; set; }
        public int tbl_BB_MagazineId { get; set; }
        public string tbl_BB_MagazineAbbreviatedTitle { get; set; }
        public string tbl_BB_MagazineTitle { get; set; }
        public string tbl_BB_MagazineISBN { get; set; }
        public string tbl_BB_MagazineISSN { get; set; }
        public Nullable<double> tbl_BB_MagazineTotalCity { get; set; }
        public Nullable<double> tbl_BB_MagazineImmediacyIndex { get; set; }
        public string tbl_BB_MagazineProperty { get; set; }
        public Nullable<int> tbl_BB_MagazineArticles { get; set; }
        public string tbl_BB_MagazineCHF { get; set; }
        public string tbl_BB_MagazineType { get; set; }
        public Nullable<int> tbl_BB_MagazineCreateYear { get; set; }
        public int tbl_BB_ScienceId { get; set; }
        public string tbl_BB_ScienceCode { get; set; }
        public string tbl_BB_ScienceName { get; set; }
        public string tbl_BB_ScienceShortName { get; set; }
    }
}
