//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_NEWS_TinTuc_ChiTiet
    {
        public int Id { get; set; }
        public Nullable<int> TinTucId { get; set; }
        public string tbl_NEWS_Tintuc_TinTucId_Ten { get; set; }
        public string Ten { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh_File { get; set; }
    }
}
