//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_CGCN_DoanhThu
    {
        public int Id { get; set; }
        public Nullable<int> CoQuanChuQuanId { get; set; }
        public string tbl_KHCN_CoQuanChuQuan_CoQuanChuQuanId_Name { get; set; }
        public string Nam { get; set; }
        public Nullable<double> DoanhThu { get; set; }
        public string GhiChu { get; set; }
    }
}
