//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_HOINGHI_BuocThucHien_Chitiet
    {
        public int Id { get; set; }
        public Nullable<int> BuocthuchienId { get; set; }
        public int tbl_HOINGHI_BuocThucHien_BuocthuchienId_Id { get; set; }
        public string Tacgia { get; set; }
        public Nullable<int> BaibaocaoId { get; set; }
        public string tbl_HOINGHI_DS_BaiBaoCao_BaibaocaoId_Name { get; set; }
        public string Thoigian { get; set; }
        public Nullable<System.DateTime> Ngaybaocao { get; set; }
    }
}
