//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_PTN_KetQuaNhiemThuDeTai
    {
        public int Id { get; set; }
        public int PhongTNId { get; set; }
        public string tbl_PTN_ThongTinChung_PhongTNId_Name { get; set; }
        public Nullable<System.DateTime> NgayNhiemThu { get; set; }
        public Nullable<int> DuAnId { get; set; }
        public string GhiChu { get; set; }
        public string KetQuaNghiemThu { get; set; }
        public string KetQuaChinh { get; set; }
    }
}
