//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_PTN_INFO_CoCauToChuc
    {
        public int Id { get; set; }
        public Nullable<int> PTNId { get; set; }
        public string tbl_PTN_INFO_ThongTinChung_PTNId_Name { get; set; }
        public string TenThanhPhan { get; set; }
        public string ChucNang { get; set; }
    }
}
