//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_BB_Magazine_IF
    {
        public int Id { get; set; }
        public Nullable<int> MagazineId { get; set; }
        public string tbl_BB_Magazine_MagazineId_Name { get; set; }
        public Nullable<int> Yearth { get; set; }
        public Nullable<double> ImpactFactor { get; set; }
    }
}
