//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_HSCB_QuaTrinhNghienCuu
    {
        public int Id { get; set; }
        public Nullable<int> MaCanBoId { get; set; }
        public string tbl_HSCB_LyLichCanBo_MaCanBoId_Ten { get; set; }
        public string DeTai { get; set; }
        public string MaSo { get; set; }
        public string NamBatDau { get; set; }
        public string NamKetThuc { get; set; }
        public Nullable<double> KinhPhi { get; set; }
        public Nullable<bool> LaChuNhiem { get; set; }
        public Nullable<bool> ThamGia { get; set; }
        public string NgayNghiemThu { get; set; }
        public string KetQua { get; set; }
    }
}
