//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_CIVINA_InStock
    {
        public int Id { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public string tbl_CJVINA_WareHouse_WarehouseId_Name { get; set; }
        public Nullable<int> ShelterId { get; set; }
        public string tbl_CJVINA_Shelter_ShelterId_Name { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string tbl_CJVINA_LoaiThucAn_ProductId_Name { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
