//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_SHTT_TapHuan_KetQua
    {
        public int Id { get; set; }
        public Nullable<int> LopTapHuanId { get; set; }
        public string tbl_SHTT_LopTapHuan_LopTapHuanId_Name { get; set; }
        public Nullable<int> SoLuongTapHuan { get; set; }
        public Nullable<int> SLCapChungChi { get; set; }
        public Nullable<int> KinhPhi { get; set; }
        public string GhiChu { get; set; }
    }
}
