//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_PTN_TinhHinhDauTu
    {
        public int Id { get; set; }
        public Nullable<int> PhongTNId { get; set; }
        public string tbl_PTN_INFO_ThongTinChung_PhongTNId_Name { get; set; }
        public Nullable<System.DateTime> TinhHinhDT { get; set; }
        public string NamTrienKhai { get; set; }
        public string NamKetThuc { get; set; }
        public string TinhHinhTH { get; set; }
        public Nullable<double> TongGT { get; set; }
        public Nullable<double> TongVon { get; set; }
        public string NguonVon { get; set; }
    }
}
