//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_BanQuanLy
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ChucNang { get; set; }
        public string NhiemVu { get; set; }
        public string DHChienLuoc { get; set; }
    }
}
