//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_DA_BUOCTH_PhieuDiem
    {
        public int Id { get; set; }
        public Nullable<int> QuaTrinhId { get; set; }
        public int tbl_DA_QuaTrinhThucHien_QuaTrinhId_Id { get; set; }
        public string HoiDong { get; set; }
        public string Ten { get; set; }
        public Nullable<double> SoDiem { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string HinhAnh_File { get; set; }
    }
}
