//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_DS_ThanhVien
    {
        public int Id { get; set; }
        public Nullable<int> BanQuanLyId { get; set; }
        public string tbl_BanQuanLy_BanQuanLyId_Name { get; set; }
        public Nullable<int> ThanhVienId { get; set; }
        public string tbl_HSCB_LyLichCanBo_ThanhVienId_Ten { get; set; }
        public Nullable<int> ChucVuId { get; set; }
        public string tbl_DM_ChucVu_TrongBan_ChucVuId_Name { get; set; }
    }
}
