//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsttbl_tbl_DA_SanPhamDeTai
    {
        public int Id { get; set; }
        public Nullable<int> DuAnId { get; set; }
        public string tbl_DA_ThongTinChung_DuAnId_Ten { get; set; }
        public Nullable<double> Dang1 { get; set; }
        public Nullable<double> Dang2 { get; set; }
        public Nullable<double> Dang3 { get; set; }
        public Nullable<double> Dang4 { get; set; }
        public Nullable<double> Dang5 { get; set; }
        public Nullable<bool> LoaiDeTaiOrDuAn { get; set; }
    }
}
