//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LVQ_BaiBaoTongKet_NhomTacGia
    {
        public string NhomTacGia { get; set; }
        public Nullable<int> Yearth { get; set; }
        public string ProName { get; set; }
        public string UnitName { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProgrameId { get; set; }
        public string ISSN { get; set; }
        public double ImpactFactor { get; set; }
        public Nullable<int> LinhVucId { get; set; }
        public int Id { get; set; }
        public string WebLink { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public Nullable<int> MagazineId { get; set; }
        public string General { get; set; }
    }
}
