//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LVQ_BaoCaoTongKet_ChiSo
    {
        public Nullable<int> Yearth { get; set; }
        public Nullable<int> ProgrameId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string ChuongTrinh { get; set; }
        public string DonVi { get; set; }
        public Nullable<double> ImpactFactor { get; set; }
        public string PaperTitle { get; set; }
        public Nullable<int> TongIF { get; set; }
        public Nullable<int> TongBB { get; set; }
    }
}
