//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LVQ_BaiBao06_IF
    {
        public int Id { get; set; }
        public string PaperTitle { get; set; }
        public Nullable<int> Yearth { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> ProgrameId { get; set; }
        public string Magazine { get; set; }
        public Nullable<int> MagazineId { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string MagazineDetail { get; set; }
        public string Abstract { get; set; }
        public Nullable<int> TypeOfAuthor { get; set; }
        public string HinhAnh_File { get; set; }
        public Nullable<int> Months { get; set; }
        public string ProjectCode { get; set; }
        public string WebLink { get; set; }
        public string NhomTacGia { get; set; }
        public Nullable<int> LinhVucId { get; set; }
        public Nullable<int> LoaiTapChiId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string UnitName { get; set; }
        public string UnitCode { get; set; }
        public string ProName { get; set; }
        public string ProCode { get; set; }
        public string AbbreviatedTitle { get; set; }
        public string MagazineName { get; set; }
        public string ISBN { get; set; }
        public string ISSN { get; set; }
        public Nullable<double> ImpactFactor { get; set; }
        public string Type { get; set; }
        public string LoaiTapChi { get; set; }
    }
}
