//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_PTN_WORKING_ChuyenGiaoCongNghe01_DonViNhanId
    {
        public int Id { get; set; }
        public int PhongTNId { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> DonViNhanId { get; set; }
        public Nullable<double> DoanhSo { get; set; }
        public string NoiDungChuyenGiao { get; set; }
        public string tbl_PTN_INFO_ThongTinChung_PhongTNId_Name { get; set; }
        public string tbl_PTN_DM_DoiTac_DonViNhanId_Ten { get; set; }
    }
}
