//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_HSCB_QuaTrinhNghienCuu01_DeTaiId
    {
        public int Id { get; set; }
        public Nullable<int> MaCanBoId { get; set; }
        public Nullable<int> DeTaiId { get; set; }
        public string MaSo { get; set; }
        public Nullable<int> NamBatDau { get; set; }
        public Nullable<int> NamKetThuc { get; set; }
        public Nullable<double> KinhPhi { get; set; }
        public Nullable<bool> LaChuNhiem { get; set; }
        public Nullable<bool> ThamGia { get; set; }
        public Nullable<System.DateTime> NgayNghiemThu { get; set; }
        public string KetQua { get; set; }
        public string tbl_HSCB_LyLichCanBo_MaCanBoId_Ten { get; set; }
        public string tbl_DA_ThongTinChung_DeTaiId_Ten { get; set; }
    }
}
