//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_Magazine_Fund
    {
        public int Id { get; set; }
        public string Ten { get; set; }
        public Nullable<double> IFLow { get; set; }
        public Nullable<double> IFHigh { get; set; }
        public Nullable<double> Fund { get; set; }
    }
}
