//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_PTN_DeTaiThucHien01_MaDeTaiId
    {
        public int Id { get; set; }
        public int MaPTNId { get; set; }
        public int MaDeTaiId { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string tbl_PTN_ThongTinChung_MaPTNId_Ten { get; set; }
        public string tbl_DA_ThongTinChung_MaDeTaiId_Ten { get; set; }
    }
}
