//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_NEWS_ThongBao_ChiTiet00_ThongBaoId
    {
        public int Id { get; set; }
        public Nullable<int> ThongBaoId { get; set; }
        public string Ten { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh_File { get; set; }
        public string tbl_NEWS_ThongBao_ThongBaoId_Ten { get; set; }
    }
}
