//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_Menu00_MaQuyen
    {
        public int Id { get; set; }
        public string Menu { get; set; }
        public string Url { get; set; }
        public int MaQuyen { get; set; }
        public Nullable<int> MenuCha { get; set; }
        public string Hinh { get; set; }
        public string tbl_Quyen_MaQuyen_Ten { get; set; }
    }
}
