//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_HSCB_BangPhatMinh00_MaCanBoId
    {
        public int Id { get; set; }
        public Nullable<int> MaCanBoId { get; set; }
        public string TenBang { get; set; }
        public string SoHieu { get; set; }
        public Nullable<int> NamCap { get; set; }
        public string NoiCap { get; set; }
        public Nullable<bool> LaTacGia { get; set; }
        public Nullable<bool> ThamGia { get; set; }
        public string SanPham { get; set; }
        public string tbl_HSCB_LyLichCanBo_MaCanBoId_Ten { get; set; }
    }
}
