//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_SHTT_VanBangBaoHo00_LoaiVanBangId
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> LoaiVanBangId { get; set; }
        public string SoBang { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string SoDon { get; set; }
        public Nullable<System.DateTime> NgayNopDon { get; set; }
        public string NguoiNop { get; set; }
        public string DiaChi { get; set; }
        public string TacGia { get; set; }
        public string tbl_SHTT_LoaiVanBang_LoaiVanBangId_Name { get; set; }
    }
}
