//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_PTN_WORKING_DeTaiCongBo00_PTNId
    {
        public int Id { get; set; }
        public Nullable<int> PTNId { get; set; }
        public Nullable<int> SanPhamId { get; set; }
        public Nullable<System.DateTime> NgayCongBo { get; set; }
        public string TieuDe { get; set; }
        public string TenTapChi { get; set; }
        public Nullable<int> LoaiTapChiId { get; set; }
        public Nullable<int> TrangBatDau { get; set; }
        public Nullable<int> TrangKetThuc { get; set; }
        public string SoHieuISBN { get; set; }
        public string SoHieuISSN { get; set; }
        public string DiemIF { get; set; }
        public string Website { get; set; }
        public string tbl_PTN_INFO_ThongTinChung_PTNId_Name { get; set; }
    }
}
