//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_PTN_DaoTaoNhanLuc00_PhongTNId
    {
        public int Id { get; set; }
        public Nullable<int> PhongTNId { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> MaNguonNhanLucId { get; set; }
        public string ThoiGian { get; set; }
        public Nullable<int> HocViId { get; set; }
        public Nullable<int> TongSo { get; set; }
        public string GhiChu { get; set; }
        public string tbl_PTN_ThongTinChung_PhongTNId_Name { get; set; }
    }
}
