//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_HSCB_ThoiGianCongTac02_MaChucVuId
    {
        public int Id { get; set; }
        public Nullable<int> MaCanBoId { get; set; }
        public Nullable<int> MaTruongId { get; set; }
        public Nullable<int> MaChucVuId { get; set; }
        public string ThoiGianBanDau { get; set; }
        public string ThoiGianKetThuc { get; set; }
        public string tbl_HSCB_LyLichCanBo_MaCanBoId_Ten { get; set; }
        public string tbl_DM_TruongVien_MaTruongId_Ten { get; set; }
        public string tbl_DM_ChucVu_MaChucVuId_Ten { get; set; }
    }
}
