//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_DHQG_HoatDongTieuBieu_ChiTiet00_HoatDongId
    {
        public int Id { get; set; }
        public Nullable<int> HoatDongId { get; set; }
        public string Ten { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh { get; set; }
        public string tbl_DHQG_HoatDongTieuBieu_HoatDongId_Name { get; set; }
    }
}
