//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_DA_QuaTrinhThucHien00_MaDuAnId
    {
        public int Id { get; set; }
        public Nullable<int> MaDuAnId { get; set; }
        public Nullable<int> MaBuocId { get; set; }
        public string ThoiGianHoanThanh { get; set; }
        public string GhiChu { get; set; }
        public string tbl_DA_ThongTinChung_MaDuAnId_Ten { get; set; }
    }
}
