//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_DHQG_NhomNghienCuu02_DonViId
    {
        public int Id { get; set; }
        public string TenNhom { get; set; }
        public Nullable<int> TruongNhom { get; set; }
        public string LanhVucChinh { get; set; }
        public string GioiThieu { get; set; }
        public Nullable<int> CTNCId { get; set; }
        public Nullable<int> DonViId { get; set; }
        public Nullable<int> PTNId { get; set; }
        public string tbl_HSCB_LyLichCanBo_TruongNhom_Ten { get; set; }
        public string tbl_DHQG_CTNC_CTNCId_Name { get; set; }
        public string tbl_DM_TruongVien_DonViId_Ten { get; set; }
    }
}
