//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_DA_BUOCTH_BienBan_ThanhLapHoiDong00_BuocTHId
    {
        public int Id { get; set; }
        public Nullable<int> BuocTHId { get; set; }
        public Nullable<System.DateTime> NgayQD { get; set; }
        public Nullable<System.DateTime> NgayTL { get; set; }
        public Nullable<double> SoThanhVien { get; set; }
        public string NoiDungTomTat { get; set; }
        public string ChuTich { get; set; }
        public string KienNghi { get; set; }
        public string HinhAnh_File { get; set; }
        public Nullable<int> DuAnId { get; set; }
        public string tbl_DM_BuocThucHien_ChiTiet_BuocTHId_Ten { get; set; }
    }
}
