//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_SHTT_KieuDangCongNghiep00_VanBangId
    {
        public int Id { get; set; }
        public Nullable<int> VanBangId { get; set; }
        public string TenKieuDang { get; set; }
        public string PhanLoai { get; set; }
        public string SoBang { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string SoDon { get; set; }
        public Nullable<System.DateTime> NgayNopDon { get; set; }
        public Nullable<System.DateTime> NgayUuTien { get; set; }
        public string MaQGUuTien { get; set; }
        public string NguoiNopDon { get; set; }
        public string DiaChi { get; set; }
        public string MaQGNguoiNop { get; set; }
        public string TenChuNhiem { get; set; }
        public string DiaChiCN { get; set; }
        public string MaQGCN { get; set; }
        public string SoPhuongAn { get; set; }
        public Nullable<System.DateTime> NgayCongBaoA { get; set; }
        public string SoCongBaoA { get; set; }
        public Nullable<System.DateTime> NgayCongBaoB { get; set; }
        public string SoCongBaoB { get; set; }
        public string tbl_SHTT_VanBangBaoHo_VanBangId_Name { get; set; }
    }
}
