//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_HSCB_BaiBao_KyYeu00_AuthorId
    {
        public int Id { get; set; }
        public Nullable<int> Yearth { get; set; }
        public string HoiNghi { get; set; }
        public string TenBai { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string SanPham { get; set; }
        public string ThơiGian { get; set; }
        public string NoiToChuc { get; set; }
        public string ISBN { get; set; }
        public Nullable<bool> HoiNghiTrongNuoc { get; set; }
        public Nullable<bool> HoiNghiQuocTe { get; set; }
        public string tbl_HSCB_LyLichCanBo_AuthorId_Ten { get; set; }
    }
}
