//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_PTN_PLAN_DaoTaoNhanLuc00_KeHoachId
    {
        public int Id { get; set; }
        public Nullable<int> KeHoachId { get; set; }
        public Nullable<int> HocViId { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string GhiChu { get; set; }
        public string TS { get; set; }
        public string ThS { get; set; }
        public string DH_CD { get; set; }
        public string Khac { get; set; }
        public Nullable<int> PhongTNId { get; set; }
        public string NamDT { get; set; }
        public string tbl_PTN_PLAN_LapKeHoachHoatDong_KeHoachId_Ten { get; set; }
    }
}
