//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_HSCB_HuongDanSinhVien01_SanPham
    {
        public int Id { get; set; }
        public Nullable<int> MaCanBoId { get; set; }
        public string TenSinhVien { get; set; }
        public string TenLuanAn { get; set; }
        public Nullable<int> NamTotNghiep { get; set; }
        public Nullable<int> BacDaoTaoId { get; set; }
        public Nullable<int> SanPham { get; set; }
        public string tbl_HSCB_LyLichCanBo_MaCanBoId_Ten { get; set; }
        public string tbl_DA_ThongTinChung_SanPham_Ten { get; set; }
    }
}
