//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_NEWS_Tintuc00_LoaiTinId
    {
        public int Id { get; set; }
        public Nullable<int> LoaiTinId { get; set; }
        public Nullable<int> PageId { get; set; }
        public string Ten { get; set; }
        public string MoTaNgan { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDuaTin { get; set; }
        public Nullable<int> NguoiDuaTinId { get; set; }
        public string NguonTin { get; set; }
        public string HinhAnh { get; set; }
        public string tbl_NEWS_LoaiTin_LoaiTinId_Name { get; set; }
    }
}
