//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_PTN_DeTaiCongBo00_SanPhamId
    {
        public int Id { get; set; }
        public Nullable<int> PTNId { get; set; }
        public Nullable<int> SanPhamId { get; set; }
        public Nullable<System.DateTime> NgayCongBo { get; set; }
        public string tbl_PTN_DM_SanPhamKHCN_SanPhamId_Ten { get; set; }
    }
}
