//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_KP_KinhPhi02_DonViId
    {
        public int Id { get; set; }
        public Nullable<int> LoaiKPId { get; set; }
        public Nullable<int> NguonVonId { get; set; }
        public Nullable<int> DonViId { get; set; }
        public Nullable<int> DVChiTietId { get; set; }
        public Nullable<int> DeTaiId { get; set; }
        public Nullable<int> DTChiTietId { get; set; }
        public string ThoiGian { get; set; }
        public string NamBatDau { get; set; }
        public string NameKetThuc { get; set; }
        public Nullable<double> TongDauTu { get; set; }
        public Nullable<double> DeXuatDV { get; set; }
        public string NamDeXuat { get; set; }
        public Nullable<double> UocThucHien { get; set; }
        public string GhiChu { get; set; }
        public string DuToanHC { get; set; }
        public Nullable<System.DateTime> Nam { get; set; }
        public Nullable<double> SoTien { get; set; }
        public string tbl_KP_LoaiKinhPhi_LoaiKPId_Name { get; set; }
        public string tbl_KP_NguonVon_NguonVonId_Name { get; set; }
        public string tbl_KP_DonVi_DonViId_Name { get; set; }
    }
}
