//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_PTN_TrangThietBi01_MaThietBiId
    {
        public int Id { get; set; }
        public int MaPTNId { get; set; }
        public int MaThietBiId { get; set; }
        public string MaQuanLyId { get; set; }
        public Nullable<int> NuocSanXuat { get; set; }
        public string HangSanXuat { get; set; }
        public string ThongSoKyThuat { get; set; }
        public Nullable<System.DateTime> ThoiGianMua { get; set; }
        public Nullable<System.DateTime> ThoiGianDuaVaoSuDung { get; set; }
        public string Nguoi_BoPhanSuDung { get; set; }
        public Nullable<double> TriGia { get; set; }
        public string TinhNang { get; set; }
        public Nullable<int> GiaTriConLai { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string tbl_PTN_ThongTinChung_MaPTNId_Ten { get; set; }
        public string tbl_DM_ThietBi_MaThietBiId_Ten { get; set; }
    }
}
