//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_CONFIG_REPORT_MULTI_DETAIL
    {
        public int Id { get; set; }
        public string TableName { get; set; }
        public string ColName { get; set; }
        public string FormName { get; set; }
        public string IsShow { get; set; }
        public string ColType { get; set; }
        public Nullable<int> OrderCol { get; set; }
        public string Parent { get; set; }
        public string ChildNode { get; set; }
    }
}
