//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_CJVINA_Shelter00_WarehouseId
    {
        public int Id { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<double> ContainerPower { get; set; }
        public string tbl_CJVINA_WareHouse_WarehouseId_Name { get; set; }
    }
}
