//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_HOINGHI_ChiTiet01_HoiNghiId
    {
        public int Id { get; set; }
        public Nullable<int> LoaiHoiNghiId { get; set; }
        public Nullable<int> HoiNghiId { get; set; }
        public Nullable<int> DiadiemId { get; set; }
        public string Noidung { get; set; }
        public string Chitiet { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> Ngaybatdau { get; set; }
        public Nullable<System.DateTime> Ngayketthuc { get; set; }
        public string Ketqua { get; set; }
        public string tbl_HOINGHI_Type_LoaiHoiNghiId_Name { get; set; }
        public string tbl_HOINGHI_DS_HN_HT_HoiNghiId_Name { get; set; }
    }
}
