//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_GIATHUONG_SV_SinhVien02_CongTrinhId
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> TruongVienId { get; set; }
        public Nullable<int> GiaiThuongId { get; set; }
        public Nullable<int> CongTrinhId { get; set; }
        public Nullable<int> NhomNganhId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> NamSinh { get; set; }
        public Nullable<int> GioiTinhId { get; set; }
        public string DanToc { get; set; }
        public string NamDaoTao { get; set; }
        public Nullable<int> NganhId { get; set; }
        public string Mobile { get; set; }
        public string DTNha { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> CanBoId { get; set; }
        public string tbl_DM_TruongVien_TruongVienId_Ten { get; set; }
        public string tbl_GIAITHUONG_SV_GiaiThuongId_Name { get; set; }
        public string tbl_TH_DM_CongTrinh_CongTrinhId_Name { get; set; }
    }
}
