//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_PTN_DichVu01_DichVu
    {
        public int Id { get; set; }
        public Nullable<int> MaPTNId { get; set; }
        public Nullable<int> DichVu { get; set; }
        public Nullable<int> SoMau { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> DoanhSo { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string tbl_PTN_ThongTinChung_MaPTNId_Ten { get; set; }
        public string tbl_DM_DichVu_DichVu_Ten { get; set; }
    }
}
