//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_BB_Science_Magazine2_KhenThuong01_DinhMucId
    {
        public int Id { get; set; }
        public Nullable<int> BaiBaoId { get; set; }
        public Nullable<bool> KhenThuong { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<int> DinhMucId { get; set; }
        public string tbl_BB_Science_Magazine2_BaiBaoId_MagazineDetail { get; set; }
        public string tbl_BB_DinhMucKhenThuong_DinhMucId_Name { get; set; }
    }
}
