//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_KP_DonVi_ChiTiet00_DonViId
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> DonViId { get; set; }
        public string tbl_KP_DonVi_DonViId_Name { get; set; }
    }
}
