//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_HSCB_BaiBao01_TypeOfAuthor
    {
        public int Id { get; set; }
        public Nullable<int> Yearth { get; set; }
        public Nullable<int> MagazineId { get; set; }
        public string MagazineDetail { get; set; }
        public string Abstract { get; set; }
        public string PaperTitle { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public Nullable<int> TypeOfAuthor { get; set; }
        public Nullable<int> DeTai { get; set; }
        public Nullable<int> ProgrameId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> Months { get; set; }
        public string WebLink { get; set; }
        public string tbl_BB_Magazine_MagazineId_Name { get; set; }
        public string tbl_HSCB_LyLichCanBo_TypeOfAuthor_Ten { get; set; }
    }
}
