//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_SY_HuongDanSuDung
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Ten { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public string FileDinhKem { get; set; }
    }
}
