//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpt_gc_tbl_HOINGHI_DS_BaiBaoCao00_KhachmoiId
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> HoiNghiId { get; set; }
        public Nullable<int> KhachmoiId { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string Mota { get; set; }
        public string tbl_HOINGHI_DS_KhachMoi_KhachmoiId_Name { get; set; }
    }
}
