//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysuserrkey
    {
        public Nullable<short> uid { get; set; }
        public string name { get; set; }
        public string colname { get; set; }
        public Nullable<short> colid { get; set; }
        public int id { get; set; }
    }
}
