//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysuserfkey
    {
        public int rkeyid { get; set; }
        public string rname { get; set; }
        public string rcolname { get; set; }
        public int fkeyid { get; set; }
        public string fname { get; set; }
        public string fcolname { get; set; }
        public Nullable<short> rkey { get; set; }
        public Nullable<short> fkey { get; set; }
    }
}
