//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysusercolumn
    {
        public string name { get; set; }
        public int tableid { get; set; }
        public byte xtype { get; set; }
        public short length { get; set; }
        public byte xprec { get; set; }
        public byte xscale { get; set; }
        public Nullable<short> colid { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<int> isnullable { get; set; }
        public Nullable<short> colorder { get; set; }
    }
}
