//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DHQG_HoatDongTieuBieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DHQG_HoatDongTieuBieu()
        {
            this.tbl_DHQG_HoatDongTieuBieu_ChiTiet = new HashSet<tbl_DHQG_HoatDongTieuBieu_ChiTiet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string TomTat { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> NguoiDangTin { get; set; }
        public Nullable<System.DateTime> NgayDangTin { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> BanQuanLyId { get; set; }
    
        public virtual tbl_BanQuanLy tbl_BanQuanLy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DHQG_HoatDongTieuBieu_ChiTiet> tbl_DHQG_HoatDongTieuBieu_ChiTiet { get; set; }
        public virtual tbl_HSCB_LyLichCanBo tbl_HSCB_LyLichCanBo { get; set; }
    }
}
