//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TH_DM_PhanBien
    {
        public int Id { get; set; }
        public Nullable<int> SinhVienId { get; set; }
        public Nullable<int> CanBo1Id { get; set; }
        public Nullable<double> Diem1 { get; set; }
        public Nullable<int> CanBo2Id { get; set; }
        public Nullable<double> Diem2 { get; set; }
        public Nullable<int> CanBo3Id { get; set; }
        public Nullable<double> Diem3 { get; set; }
        public Nullable<double> TrungBinh { get; set; }
        public string XepHang { get; set; }
    
        public virtual tbl_GIAITHUONG_SV_SinhVien tbl_GIAITHUONG_SV_SinhVien { get; set; }
        public virtual tbl_HSCB_LyLichCanBo tbl_HSCB_LyLichCanBo { get; set; }
        public virtual tbl_HSCB_LyLichCanBo tbl_HSCB_LyLichCanBo1 { get; set; }
        public virtual tbl_HSCB_LyLichCanBo tbl_HSCB_LyLichCanBo2 { get; set; }
    }
}
