//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HSCB_UngDungThucTien
    {
        public int Id { get; set; }
        public Nullable<int> MaCanBoId { get; set; }
        public string TenCongNghe { get; set; }
        public string HinhThuc { get; set; }
        public string NamChuyenGiao { get; set; }
        public string SanPham { get; set; }
    
        public virtual tbl_HSCB_LyLichCanBo tbl_HSCB_LyLichCanBo { get; set; }
    }
}
