//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PTN_DM_SanPhamKHCN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_PTN_DM_SanPhamKHCN()
        {
            this.tbl_PTN_WORKING_DeTaiCongBo = new HashSet<tbl_PTN_WORKING_DeTaiCongBo>();
        }
    
        public int Id { get; set; }
        public string Ten { get; set; }
        public string Nam { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<int> PTNId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_WORKING_DeTaiCongBo> tbl_PTN_WORKING_DeTaiCongBo { get; set; }
    }
}
