//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DHQG_DSThanhVien
    {
        public int Id { get; set; }
        public Nullable<int> NhomNghienCuuId { get; set; }
        public Nullable<int> ThanhVienId { get; set; }
    
        public virtual tbl_DHQG_NhomNghienCuu tbl_DHQG_NhomNghienCuu { get; set; }
        public virtual tbl_HSCB_LyLichCanBo tbl_HSCB_LyLichCanBo { get; set; }
    }
}
