//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DA_ThongTinChung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DA_ThongTinChung()
        {
            this.tbl_DA_CanBoThamGia = new HashSet<tbl_DA_CanBoThamGia>();
            this.tbl_DA_QuaTrinhThucHien = new HashSet<tbl_DA_QuaTrinhThucHien>();
            this.tbl_DA_SanPhamDeTai = new HashSet<tbl_DA_SanPhamDeTai>();
            this.tbl_PTN_WORKING_KetQuaNhiemThuDeTai = new HashSet<tbl_PTN_WORKING_KetQuaNhiemThuDeTai>();
        }
    
        public int Id { get; set; }
        public string Ten { get; set; }
        public string MaSo { get; set; }
        public Nullable<int> LoaiDuanId { get; set; }
        public Nullable<int> ThuocChuongTrinhId { get; set; }
        public Nullable<int> ThuocLinhVucId { get; set; }
        public Nullable<int> ChuNhiemId { get; set; }
        public Nullable<int> DongChuNhiemId { get; set; }
        public string ThoiGianBatDau { get; set; }
        public string ThoiGianKetThuc { get; set; }
        public string SoThang { get; set; }
        public Nullable<double> KinhPhi { get; set; }
        public Nullable<double> KinhPhiSuNghiepKH { get; set; }
        public Nullable<int> CoQuanCapKinhPhi { get; set; }
        public Nullable<int> CoQuanChuQuan { get; set; }
        public Nullable<int> CoQuanChuTri { get; set; }
        public string DiaChiUngDung { get; set; }
        public string MucTieu { get; set; }
        public string NoiDung { get; set; }
        public string SanPham { get; set; }
        public string TomTatKetQua { get; set; }
        public string TomTatKetQuaTiengAnh { get; set; }
        public string KhaNangUngDung { get; set; }
        public string TinhTrangThucHien { get; set; }
        public string NgayCapNhat { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual tbl_BB_Programe tbl_BB_Programe { get; set; }
        public virtual tbl_BB_Unit tbl_BB_Unit { get; set; }
        public virtual tbl_BB_Unit tbl_BB_Unit1 { get; set; }
        public virtual tbl_BB_Unit tbl_BB_Unit2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_CanBoThamGia> tbl_DA_CanBoThamGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_QuaTrinhThucHien> tbl_DA_QuaTrinhThucHien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_SanPhamDeTai> tbl_DA_SanPhamDeTai { get; set; }
        public virtual tbl_DM_LinhVuc tbl_DM_LinhVuc { get; set; }
        public virtual tbl_DM_LoaiDuAn tbl_DM_LoaiDuAn { get; set; }
        public virtual tbl_HSCB_LyLichCanBo tbl_HSCB_LyLichCanBo { get; set; }
        public virtual tbl_HSCB_LyLichCanBo tbl_HSCB_LyLichCanBo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_WORKING_KetQuaNhiemThuDeTai> tbl_PTN_WORKING_KetQuaNhiemThuDeTai { get; set; }
    }
}
