//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BB_Programe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_BB_Programe()
        {
            this.tbl_DA_ThongTinChung = new HashSet<tbl_DA_ThongTinChung>();
            this.tbl_DK_DeTai_Loai_1 = new HashSet<tbl_DK_DeTai_Loai_1>();
            this.tbl_DK_DeTai_Loai_2 = new HashSet<tbl_DK_DeTai_Loai_2>();
            this.tbl_DT_HDN_NN_Content = new HashSet<tbl_DT_HDN_NN_Content>();
            this.tbl_HSCB_BaiBao_KyYeu = new HashSet<tbl_HSCB_BaiBao_KyYeu>();
            this.tbl_HSCB_BaiBao = new HashSet<tbl_HSCB_BaiBao>();
            this.tbl_KHCN_ThongTinToChuc = new HashSet<tbl_KHCN_ThongTinToChuc>();
            this.tbl_BB_Science_Magazine2 = new HashSet<tbl_BB_Science_Magazine2>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Note { get; set; }
        public Nullable<int> orderCol { get; set; }
        public Nullable<int> Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_ThongTinChung> tbl_DA_ThongTinChung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DK_DeTai_Loai_1> tbl_DK_DeTai_Loai_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DK_DeTai_Loai_2> tbl_DK_DeTai_Loai_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DT_HDN_NN_Content> tbl_DT_HDN_NN_Content { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HSCB_BaiBao_KyYeu> tbl_HSCB_BaiBao_KyYeu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HSCB_BaiBao> tbl_HSCB_BaiBao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KHCN_ThongTinToChuc> tbl_KHCN_ThongTinToChuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BB_Science_Magazine2> tbl_BB_Science_Magazine2 { get; set; }
    }
}
