//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TK_Quyen_NhomQuyen
    {
        public int Id { get; set; }
        public int NhomQuyenId { get; set; }
        public int MaQuyenId { get; set; }
        public string FormName { get; set; }
        public string URL { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> isInserted { get; set; }
        public Nullable<bool> isUpdate { get; set; }
        public Nullable<bool> isView { get; set; }
    
        public virtual tbl_TK_NhomQuyen tbl_TK_NhomQuyen { get; set; }
        public virtual tbl_TK_Quyen tbl_TK_Quyen { get; set; }
    }
}
