//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GIAITHUONG_SV_BuocThucHien
    {
        public int Id { get; set; }
        public Nullable<int> GiaiThuongId { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayThuchien { get; set; }
        public string Ketqua { get; set; }
        public string HinhAnhFile { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tbl_GIAITHUONG_SV tbl_GIAITHUONG_SV { get; set; }
    }
}
