//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KHCN_CoQuanChuQuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_KHCN_CoQuanChuQuan()
        {
            this.tbl_CGCN_DoanhThu = new HashSet<tbl_CGCN_DoanhThu>();
            this.tbl_KHCN_ThongTinToChuc = new HashSet<tbl_KHCN_ThongTinToChuc>();
            this.tbl_SHTT_QuanTriVien = new HashSet<tbl_SHTT_QuanTriVien>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CGCN_DoanhThu> tbl_CGCN_DoanhThu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KHCN_ThongTinToChuc> tbl_KHCN_ThongTinToChuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SHTT_QuanTriVien> tbl_SHTT_QuanTriVien { get; set; }
    }
}
