//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DA_QuaTrinhThucHien_ChiTiet
    {
        public int Id { get; set; }
        public Nullable<int> QuatrinhthuchienId { get; set; }
        public string Noidung1 { get; set; }
        public string Noidung2 { get; set; }
    
        public virtual tbl_DA_QuaTrinhThucHien tbl_DA_QuaTrinhThucHien { get; set; }
    }
}
