//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SHTT_Thongtinchung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SHTT_Thongtinchung()
        {
            this.tbl_PTN_WORKING_HoatDongSoHuuTriTue = new HashSet<tbl_PTN_WORKING_HoatDongSoHuuTriTue>();
            this.tbl_SHTT_Thongtinchung_BuocThucHien = new HashSet<tbl_SHTT_Thongtinchung_BuocThucHien>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string TacgiaName { get; set; }
        public string Noidungdangky { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_WORKING_HoatDongSoHuuTriTue> tbl_PTN_WORKING_HoatDongSoHuuTriTue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SHTT_Thongtinchung_BuocThucHien> tbl_SHTT_Thongtinchung_BuocThucHien { get; set; }
    }
}
