//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DA_QuiTrinhThucHien
    {
        public int Id { get; set; }
        public Nullable<int> MaLoaiDuAnId { get; set; }
        public Nullable<int> MaBuocThucHien { get; set; }
        public Nullable<int> OrderCol { get; set; }
    
        public virtual tbl_DM_LoaiDuAn tbl_DM_LoaiDuAn { get; set; }
        public virtual tbl_DM_BuocThucHien_ChiTiet tbl_DM_BuocThucHien_ChiTiet { get; set; }
    }
}
