//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HOINGHI_DS_BaiBaoCao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_HOINGHI_DS_BaiBaoCao()
        {
            this.tbl_HOINGHI_BuocThucHien_Chitiet = new HashSet<tbl_HOINGHI_BuocThucHien_Chitiet>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> HoiNghiId { get; set; }
        public Nullable<int> KhachmoiId { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string Mota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HOINGHI_BuocThucHien_Chitiet> tbl_HOINGHI_BuocThucHien_Chitiet { get; set; }
        public virtual tbl_HOINGHI_DS_HN_HT tbl_HOINGHI_DS_HN_HT { get; set; }
        public virtual tbl_HOINGHI_DS_KhachMoi tbl_HOINGHI_DS_KhachMoi { get; set; }
    }
}
