//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HSCB_TrinhDoNgoaiNgu
    {
        public int Id { get; set; }
        public Nullable<int> MaCanBoId { get; set; }
        public Nullable<int> NgoaiNguId { get; set; }
        public Nullable<int> Nghe { get; set; }
        public Nullable<int> Noi { get; set; }
        public Nullable<int> Viet { get; set; }
        public Nullable<int> Doc { get; set; }
    
        public virtual tbl_DM_CapDo tbl_DM_CapDo { get; set; }
        public virtual tbl_DM_CapDo tbl_DM_CapDo1 { get; set; }
        public virtual tbl_DM_CapDo tbl_DM_CapDo2 { get; set; }
        public virtual tbl_DM_CapDo tbl_DM_CapDo3 { get; set; }
        public virtual tbl_DM_NgoaiNgu tbl_DM_NgoaiNgu { get; set; }
        public virtual tbl_HSCB_LyLichCanBo tbl_HSCB_LyLichCanBo { get; set; }
    }
}
