//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SHTT_Giaynhanxet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SHTT_Giaynhanxet()
        {
            this.tbl_SHTT_Giaynhanxet_BangiamKhao = new HashSet<tbl_SHTT_Giaynhanxet_BangiamKhao>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Tomtat { get; set; }
        public string KetquaNX { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string Diemso { get; set; }
    
        public virtual tbl_SHTT_BuocChung tbl_SHTT_BuocChung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SHTT_Giaynhanxet_BangiamKhao> tbl_SHTT_Giaynhanxet_BangiamKhao { get; set; }
    }
}
