//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PTN_DM_PhanLoaiPhongThiNghiem
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Ten { get; set; }
        public string NameNonUnicode { get; set; }
        public Nullable<int> orderCol { get; set; }
    }
}
