//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PTN_INFO_TrangThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_PTN_INFO_TrangThietBi()
        {
            this.tbl_PTN_PLAN_DeXuatCapTrangThietBi = new HashSet<tbl_PTN_PLAN_DeXuatCapTrangThietBi>();
            this.tbl_PTN_PhuLuc_2 = new HashSet<tbl_PTN_PhuLuc_2>();
            this.tbl_PTN_PhuLuc_3 = new HashSet<tbl_PTN_PhuLuc_3>();
            this.tbl_PTN_PhuLuc_4 = new HashSet<tbl_PTN_PhuLuc_4>();
        }
    
        public int Id { get; set; }
        public int PhongTNId { get; set; }
        public int ThietBiId { get; set; }
        public Nullable<int> QuocGiaId { get; set; }
        public string HangSanXuat { get; set; }
        public string ThoiGianMua { get; set; }
        public string ThoiGianDuaVaoSuDung { get; set; }
        public string CongDung { get; set; }
        public string ThongSoKyThuat { get; set; }
        public Nullable<double> TriGia { get; set; }
        public string TanSuat { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tbl_DM_QuocGia tbl_DM_QuocGia { get; set; }
        public virtual tbl_DM_ThietBi tbl_DM_ThietBi { get; set; }
        public virtual tbl_PTN_INFO_ThongTinChung tbl_PTN_INFO_ThongTinChung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_PLAN_DeXuatCapTrangThietBi> tbl_PTN_PLAN_DeXuatCapTrangThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_PhuLuc_2> tbl_PTN_PhuLuc_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_PhuLuc_3> tbl_PTN_PhuLuc_3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_PhuLuc_4> tbl_PTN_PhuLuc_4 { get; set; }
    }
}
