//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DK_DeTai_Loai_2
    {
        public int Id { get; set; }
        public string TenDeTai { get; set; }
        public Nullable<int> ProgrameId { get; set; }
        public string LyDoDeXuat { get; set; }
        public string XuatXu { get; set; }
        public string GiaiTrinh { get; set; }
        public string MucTieu { get; set; }
        public string YeuCau { get; set; }
        public string KinhPhi { get; set; }
        public string ThoiGian { get; set; }
        public string KhaNang { get; set; }
        public string NhuCauTT { get; set; }
        public string ThongTinKhac { get; set; }
        public Nullable<int> Nam { get; set; }
        public string Email_NG { get; set; }
        public string HoTen_NG { get; set; }
        public string DienThoai_NG { get; set; }
        public string NoiDungPhanHoi { get; set; }
        public Nullable<bool> DaNhan { get; set; }
        public Nullable<bool> DaTrungTuyen { get; set; }
        public Nullable<bool> DaChinhSua { get; set; }
        public Nullable<bool> DaPhanHoi { get; set; }
        public Nullable<bool> DaLoai { get; set; }
        public string MaSoBiMat { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual tbl_BB_Programe tbl_BB_Programe { get; set; }
    }
}
