//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TH_DM_CoQuanNhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TH_DM_CoQuanNhan()
        {
            this.tbl_TH_CongVanDen = new HashSet<tbl_TH_CongVanDen>();
            this.tbl_TH_CongVanDi = new HashSet<tbl_TH_CongVanDi>();
            this.tbl_TH_QuyetDinhDen = new HashSet<tbl_TH_QuyetDinhDen>();
            this.tbl_TH_QuyetDinhDi = new HashSet<tbl_TH_QuyetDinhDi>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TH_CongVanDen> tbl_TH_CongVanDen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TH_CongVanDi> tbl_TH_CongVanDi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TH_QuyetDinhDen> tbl_TH_QuyetDinhDen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TH_QuyetDinhDi> tbl_TH_QuyetDinhDi { get; set; }
    }
}
