//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PTN_WORKING_DaoTaoNhanLuc
    {
        public int Id { get; set; }
        public Nullable<int> PhongTNId { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> MaNguonNhanLucId { get; set; }
        public Nullable<int> HocVienId { get; set; }
        public Nullable<System.DateTime> NgayNhapHoc { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> HocViId { get; set; }
        public string GhiChu { get; set; }
        public string TS { get; set; }
        public string ThS { get; set; }
        public string DH_CD { get; set; }
        public string Khac { get; set; }
        public string Nam { get; set; }
        public string TongSo { get; set; }
    
        public virtual tbl_DM_DaoTaoNhanLuc tbl_DM_DaoTaoNhanLuc { get; set; }
        public virtual tbl_DM_HocVi tbl_DM_HocVi { get; set; }
        public virtual tbl_PTN_DM_HocVien tbl_PTN_DM_HocVien { get; set; }
        public virtual tbl_PTN_INFO_ThongTinChung tbl_PTN_INFO_ThongTinChung { get; set; }
    }
}
