//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SHTT_TapHuan_ThongBao
    {
        public int Id { get; set; }
        public string SoThongBao { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string NoiThongBao { get; set; }
        public Nullable<int> LopTapHuanId { get; set; }
        public string DiaDiem { get; set; }
        public string NoiDung { get; set; }
        public string NoiNhan { get; set; }
        public string HinhAnhFile { get; set; }
        public string NguoiDuyet { get; set; }
    
        public virtual tbl_SHTT_LopTapHuan tbl_SHTT_LopTapHuan { get; set; }
    }
}
