//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CIVINA_InStock
    {
        public int Id { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<int> ShelterId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual tbl_CJVINA_Shelter tbl_CJVINA_Shelter { get; set; }
        public virtual tbl_CJVINA_WareHouse tbl_CJVINA_WareHouse { get; set; }
        public virtual tbl_CJVINA_LoaiThucAn tbl_CJVINA_LoaiThucAn { get; set; }
    }
}
