//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GOBAL
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public Nullable<bool> bBuild { get; set; }
        public string ImagePath { get; set; }
        public string CurParentName { get; set; }
        public string FileChangeCode { get; set; }
    }
}
