//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DT_HDN_NN_Content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DT_HDN_NN_Content()
        {
            this.tbl_DT_HDN_NN = new HashSet<tbl_DT_HDN_NN>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProgrameId { get; set; }
        public string ChucNang { get; set; }
        public string NhiemVu { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tbl_BB_Programe tbl_BB_Programe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DT_HDN_NN> tbl_DT_HDN_NN { get; set; }
    }
}
