//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SHTT_BienNhan
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Tomtat { get; set; }
        public string NoidungBienNhan { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string SoBienNhan { get; set; }
        public Nullable<int> NguoiNhanId { get; set; }
        public Nullable<int> NguoiGoiId { get; set; }
    
        public virtual tbl_HSCB_LyLichCanBo tbl_HSCB_LyLichCanBo { get; set; }
        public virtual tbl_HSCB_LyLichCanBo tbl_HSCB_LyLichCanBo1 { get; set; }
        public virtual tbl_SHTT_BuocChung tbl_SHTT_BuocChung { get; set; }
    }
}
