//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DK_DeTai_NhanVaTraLoi
    {
        public int DeTaiId { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> Nhan { get; set; }
        public Nullable<bool> DeTaiLoi { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<bool> DuocChapNhan { get; set; }
        public Nullable<bool> HDN_TuyenChon { get; set; }
        public Nullable<long> DaPhanHoi { get; set; }
    }
}
