//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CJVINA_Shelter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CJVINA_Shelter()
        {
            this.tbl_CIVINA_InStock = new HashSet<tbl_CIVINA_InStock>();
        }
    
        public int Id { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<double> ContainerPower { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CIVINA_InStock> tbl_CIVINA_InStock { get; set; }
        public virtual tbl_CJVINA_WareHouse tbl_CJVINA_WareHouse { get; set; }
    }
}
