//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CJVINA_InFact
    {
        public int Id { get; set; }
        public Nullable<int> FormularId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> WorkingNoteId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Error { get; set; }
    
        public virtual tbl_CJVINA_Formula tbl_CJVINA_Formula { get; set; }
        public virtual tbl_CJVINA_LoaiThucAn tbl_CJVINA_LoaiThucAn { get; set; }
        public virtual tbl_CJVINA_WorkingNote_Detail tbl_CJVINA_WorkingNote_Detail { get; set; }
    }
}
