//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GIAITHUONG_SV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_GIAITHUONG_SV()
        {
            this.tbl_GIAITHUONG_SV_BuocThucHien = new HashSet<tbl_GIAITHUONG_SV_BuocThucHien>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> GiaithuongTypeId { get; set; }
        public Nullable<int> DonViToChucId { get; set; }
        public string Noidung { get; set; }
        public string Chitiet { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> Ngaybatdau { get; set; }
        public Nullable<System.DateTime> Ngayketthuc { get; set; }
        public string Ketqua { get; set; }
    
        public virtual tbl_GIAITHUONG_DonViToChuc tbl_GIAITHUONG_DonViToChuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GIAITHUONG_SV_BuocThucHien> tbl_GIAITHUONG_SV_BuocThucHien { get; set; }
        public virtual tbl_GIAITHUONG_SV_Type tbl_GIAITHUONG_SV_Type { get; set; }
    }
}
