//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PTN_TinhHinhDauTu
    {
        public int Id { get; set; }
        public Nullable<int> PhongTNId { get; set; }
        public string TinhHinhDT { get; set; }
        public string NamTrienKhai { get; set; }
        public string NamKetThuc { get; set; }
        public string TinhHinhTH { get; set; }
        public string TongGT { get; set; }
        public string TongVon { get; set; }
        public string NguonVon { get; set; }
    
        public virtual tbl_PTN_INFO_ThongTinChung tbl_PTN_INFO_ThongTinChung { get; set; }
    }
}
