//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SHTT_Thongtinchung_BuocThucHien
    {
        public int Id { get; set; }
        public string Ten { get; set; }
        public Nullable<int> SHTTId { get; set; }
        public Nullable<int> TrangthaithuchienId { get; set; }
        public Nullable<int> Buocthuchiend { get; set; }
        public Nullable<System.DateTime> Ngaybatdau { get; set; }
        public Nullable<System.DateTime> Ngayketthuc { get; set; }
    
        public virtual tbl_SHTT_BuocChung tbl_SHTT_BuocChung { get; set; }
        public virtual tbl_SHTT_Thongtinchung tbl_SHTT_Thongtinchung { get; set; }
    }
}
