//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SHTT_LopTapHuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SHTT_LopTapHuan()
        {
            this.tbl_SHTT_DanhSachLopTapHuan = new HashSet<tbl_SHTT_DanhSachLopTapHuan>();
            this.tbl_SHTT_TapHuan_KetQua = new HashSet<tbl_SHTT_TapHuan_KetQua>();
            this.tbl_SHTT_TapHuan_ThongBao = new HashSet<tbl_SHTT_TapHuan_ThongBao>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SHTT_DanhSachLopTapHuan> tbl_SHTT_DanhSachLopTapHuan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SHTT_TapHuan_KetQua> tbl_SHTT_TapHuan_KetQua { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SHTT_TapHuan_ThongBao> tbl_SHTT_TapHuan_ThongBao { get; set; }
    }
}
