//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DM_ThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DM_ThietBi()
        {
            this.tbl_PTN_INFO_TrangThietBiPhu = new HashSet<tbl_PTN_INFO_TrangThietBiPhu>();
            this.tbl_PTN_INFO_TrangThietBi = new HashSet<tbl_PTN_INFO_TrangThietBi>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Ten { get; set; }
        public string CongDung { get; set; }
        public string NameNonunicode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_INFO_TrangThietBiPhu> tbl_PTN_INFO_TrangThietBiPhu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_INFO_TrangThietBi> tbl_PTN_INFO_TrangThietBi { get; set; }
    }
}
