//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BB_Magazine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_BB_Magazine()
        {
            this.tbl_BB_Science_Magazine2 = new HashSet<tbl_BB_Science_Magazine2>();
            this.tbl_BB_Magazine_IF = new HashSet<tbl_BB_Magazine_IF>();
        }
    
        public int Id { get; set; }
        public string AbbreviatedTitle { get; set; }
        public string Name { get; set; }
        public string ISBN { get; set; }
        public string ISSN { get; set; }
        public Nullable<double> TotalCity { get; set; }
        public Nullable<double> ImmediacyIndex { get; set; }
        public string Property { get; set; }
        public Nullable<int> Articles { get; set; }
        public string CHF { get; set; }
        public string Type { get; set; }
        public Nullable<int> CreateYear { get; set; }
        public string SCI { get; set; }
        public string SCI_E { get; set; }
        public string ISSI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BB_Science_Magazine2> tbl_BB_Science_Magazine2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BB_Magazine_IF> tbl_BB_Magazine_IF { get; set; }
    }
}
