//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PTN_INFO_PhanBoNhanLuc
    {
        public int Id { get; set; }
        public Nullable<int> PTNId { get; set; }
        public Nullable<int> CanBoId { get; set; }
        public string ChuyenNganh { get; set; }
        public Nullable<int> HocVi { get; set; }
        public Nullable<int> ChucVuId { get; set; }
        public Nullable<bool> CanBoCoHuu { get; set; }
        public string Email { get; set; }
        public Nullable<bool> TruongNhom { get; set; }
    
        public virtual tbl_DM_ChucVu tbl_DM_ChucVu { get; set; }
        public virtual tbl_DM_HocVi tbl_DM_HocVi { get; set; }
        public virtual tbl_HSCB_LyLichCanBo tbl_HSCB_LyLichCanBo { get; set; }
        public virtual tbl_PTN_INFO_ThongTinChung tbl_PTN_INFO_ThongTinChung { get; set; }
    }
}
