//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PTN_INFO_ThongTinChung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_PTN_INFO_ThongTinChung()
        {
            this.tbl_DHQG_NhomNghienCuu = new HashSet<tbl_DHQG_NhomNghienCuu>();
            this.tbl_HSCB_LyLichCanBo = new HashSet<tbl_HSCB_LyLichCanBo>();
            this.tbl_PTN_INFO_CoCauToChuc = new HashSet<tbl_PTN_INFO_CoCauToChuc>();
            this.tbl_PTN_INFO_PhanBoNhanLuc = new HashSet<tbl_PTN_INFO_PhanBoNhanLuc>();
            this.tbl_PTN_WORKING_ChuyenGiaoCongNghe = new HashSet<tbl_PTN_WORKING_ChuyenGiaoCongNghe>();
            this.tbl_PTN_WORKING_DaoTaoNhanLuc = new HashSet<tbl_PTN_WORKING_DaoTaoNhanLuc>();
            this.tbl_PTN_WORKING_DoanhThuDichVu = new HashSet<tbl_PTN_WORKING_DoanhThuDichVu>();
            this.tbl_PTN_WORKING_HoatDongSoHuuTriTue = new HashSet<tbl_PTN_WORKING_HoatDongSoHuuTriTue>();
            this.tbl_PTN_INFO_TrangThietBiPhu = new HashSet<tbl_PTN_INFO_TrangThietBiPhu>();
            this.tbl_PTN_WORKING_KetQuaNhiemThuDeTai = new HashSet<tbl_PTN_WORKING_KetQuaNhiemThuDeTai>();
            this.tbl_PTN_PLAN_DaoTaoNhanLuc = new HashSet<tbl_PTN_PLAN_DaoTaoNhanLuc>();
            this.tbl_PTN_PLAN_LapKeHoachHoatDong = new HashSet<tbl_PTN_PLAN_LapKeHoachHoatDong>();
            this.tbl_PTN_PLAN_TuyenDung = new HashSet<tbl_PTN_PLAN_TuyenDung>();
            this.tbl_PTN_TinhHinhDauTu = new HashSet<tbl_PTN_TinhHinhDauTu>();
            this.tbl_PTN_INFO_TrangThietBi = new HashSet<tbl_PTN_INFO_TrangThietBi>();
            this.tbl_PTN_WORKING_DeTaiCongBo = new HashSet<tbl_PTN_WORKING_DeTaiCongBo>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string TenVietTat { get; set; }
        public string TenGiaoDich { get; set; }
        public string TenGiaoDichVT { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Fax { get; set; }
        public Nullable<int> PhanLoaiId { get; set; }
        public Nullable<int> PhanCapId { get; set; }
        public Nullable<int> TruongPhongId { get; set; }
        public Nullable<int> TruongVienId { get; set; }
        public string ChucNangNhiemVu { get; set; }
        public string DoiTuongPhucVu { get; set; }
        public string DienTich { get; set; }
        public string NameNonUnicode { get; set; }
        public string TransNameNonUnicode { get; set; }
        public Nullable<int> ParentCode { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string LanhVucHoatDong { get; set; }
        public string ChucNangNghienCuuChinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DHQG_NhomNghienCuu> tbl_DHQG_NhomNghienCuu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HSCB_LyLichCanBo> tbl_HSCB_LyLichCanBo { get; set; }
        public virtual tbl_HSCB_LyLichCanBo tbl_HSCB_LyLichCanBo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_INFO_CoCauToChuc> tbl_PTN_INFO_CoCauToChuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_INFO_PhanBoNhanLuc> tbl_PTN_INFO_PhanBoNhanLuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_WORKING_ChuyenGiaoCongNghe> tbl_PTN_WORKING_ChuyenGiaoCongNghe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_WORKING_DaoTaoNhanLuc> tbl_PTN_WORKING_DaoTaoNhanLuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_WORKING_DoanhThuDichVu> tbl_PTN_WORKING_DoanhThuDichVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_WORKING_HoatDongSoHuuTriTue> tbl_PTN_WORKING_HoatDongSoHuuTriTue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_INFO_TrangThietBiPhu> tbl_PTN_INFO_TrangThietBiPhu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_WORKING_KetQuaNhiemThuDeTai> tbl_PTN_WORKING_KetQuaNhiemThuDeTai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_PLAN_DaoTaoNhanLuc> tbl_PTN_PLAN_DaoTaoNhanLuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_PLAN_LapKeHoachHoatDong> tbl_PTN_PLAN_LapKeHoachHoatDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_PLAN_TuyenDung> tbl_PTN_PLAN_TuyenDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_TinhHinhDauTu> tbl_PTN_TinhHinhDauTu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_INFO_TrangThietBi> tbl_PTN_INFO_TrangThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_WORKING_DeTaiCongBo> tbl_PTN_WORKING_DeTaiCongBo { get; set; }
    }
}
