//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HSCB_QuaTrinhDaoTao
    {
        public int Id { get; set; }
        public Nullable<int> MaCanBoId { get; set; }
        public Nullable<int> BacDaoTaoId { get; set; }
        public string ThoiGian { get; set; }
        public string NoiDaoTao { get; set; }
        public string ChuyenNganh { get; set; }
        public string TenLuanAn { get; set; }
    
        public virtual tbl_DM_BacDaoTao tbl_DM_BacDaoTao { get; set; }
        public virtual tbl_HSCB_LyLichCanBo tbl_HSCB_LyLichCanBo { get; set; }
    }
}
