//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HOINGHI_DS_KhachMoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_HOINGHI_DS_KhachMoi()
        {
            this.tbl_HOINGHI_DS_BaiBaoCao = new HashSet<tbl_HOINGHI_DS_BaiBaoCao>();
        }
    
        public int Id { get; set; }
        public Nullable<int> HoiNghiId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> LinhVucId { get; set; }
        public Nullable<int> HocViId { get; set; }
        public Nullable<int> TruongVienId { get; set; }
        public Nullable<int> ChucvuId { get; set; }
        public string Mobile { get; set; }
        public string DTNha { get; set; }
        public Nullable<bool> BaiBaoCao { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<int> DiaDiemId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HOINGHI_DS_BaiBaoCao> tbl_HOINGHI_DS_BaiBaoCao { get; set; }
        public virtual tbl_HOINGHI_DS_HN_HT tbl_HOINGHI_DS_HN_HT { get; set; }
    }
}
