//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SHTT_SangChe
    {
        public int Id { get; set; }
        public Nullable<int> VanBangId { get; set; }
        public string SoBang { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string IPC { get; set; }
        public string SoDon { get; set; }
        public Nullable<System.DateTime> NgayNopDon { get; set; }
        public string CongBoBang { get; set; }
        public string CongBoDon { get; set; }
        public string NguoiNopDon { get; set; }
        public string DiaChi { get; set; }
        public string TacGia { get; set; }
        public string DaiDienSHTT { get; set; }
        public string TenSangChe { get; set; }
        public string TomTatSangChe { get; set; }
    
        public virtual tbl_SHTT_VanBangBaoHo tbl_SHTT_VanBangBaoHo { get; set; }
    }
}
