//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KHCN_ThongTinToChuc
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> LoaiToChucId { get; set; }
        public string SoQuyetDinh { get; set; }
        public Nullable<int> NhomNganhId { get; set; }
        public string LinhVuc { get; set; }
        public Nullable<int> CoQuanChuQuanId { get; set; }
        public string LanhDao { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> OrderCol { get; set; }
    
        public virtual tbl_BB_Programe tbl_BB_Programe { get; set; }
        public virtual tbl_KHCN_CoQuanChuQuan tbl_KHCN_CoQuanChuQuan { get; set; }
        public virtual tbl_KHCN_LoaiToChuc tbl_KHCN_LoaiToChuc { get; set; }
    }
}
