//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NEWS_LoiGioiThieu
    {
        public int Id { get; set; }
        public Nullable<int> PageId { get; set; }
        public string Ten { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDuaTin { get; set; }
    
        public virtual tbl_NEWS_DM_Page tbl_NEWS_DM_Page { get; set; }
    }
}
