//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mailisa_CONFIG_DETAIL
    {
        public int Id { get; set; }
        public string Tab { get; set; }
        public string TableName { get; set; }
        public string FormName { get; set; }
        public Nullable<int> ParentTab { get; set; }
        public Nullable<int> Detail { get; set; }
        public Nullable<int> MultiOrSingle { get; set; }
        public string DetailBtnName { get; set; }
        public Nullable<int> ConfigId { get; set; }
        public Nullable<int> mLevel { get; set; }
    }
}
