//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DM_ChucVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DM_ChucVu()
        {
            this.tbl_HSCB_LyLichCanBo = new HashSet<tbl_HSCB_LyLichCanBo>();
            this.tbl_PTN_INFO_PhanBoNhanLuc = new HashSet<tbl_PTN_INFO_PhanBoNhanLuc>();
        }
    
        public int Id { get; set; }
        public string Ten { get; set; }
        public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HSCB_LyLichCanBo> tbl_HSCB_LyLichCanBo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PTN_INFO_PhanBoNhanLuc> tbl_PTN_INFO_PhanBoNhanLuc { get; set; }
    }
}
