//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BB_DinhMucKhenThuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_BB_DinhMucKhenThuong()
        {
            this.tbl_BB_Science_Magazine2_KhenThuong = new HashSet<tbl_BB_Science_Magazine2_KhenThuong>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> IFMin { get; set; }
        public Nullable<double> IFMax { get; set; }
        public Nullable<double> Gia { get; set; }
        public string NgayLap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BB_Science_Magazine2_KhenThuong> tbl_BB_Science_Magazine2_KhenThuong { get; set; }
    }
}
