//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HOINGHI_DS_HN_HT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_HOINGHI_DS_HN_HT()
        {
            this.tbl_HOINGHI_BuocThucHien = new HashSet<tbl_HOINGHI_BuocThucHien>();
            this.tbl_HOINGHI_ChiPhi = new HashSet<tbl_HOINGHI_ChiPhi>();
            this.tbl_HOINGHI_ChiTiet = new HashSet<tbl_HOINGHI_ChiTiet>();
            this.tbl_HOINGHI_DS_BaiBaoCao = new HashSet<tbl_HOINGHI_DS_BaiBaoCao>();
            this.tbl_HOINGHI_DS_KhachMoi = new HashSet<tbl_HOINGHI_DS_KhachMoi>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> LoaiHoiNghiId { get; set; }
        public Nullable<int> DVThucHienId { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public Nullable<int> DiaDiemId { get; set; }
        public Nullable<int> SoLuongKhachMoi { get; set; }
        public Nullable<double> TongKinhPhi { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HOINGHI_BuocThucHien> tbl_HOINGHI_BuocThucHien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HOINGHI_ChiPhi> tbl_HOINGHI_ChiPhi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HOINGHI_ChiTiet> tbl_HOINGHI_ChiTiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HOINGHI_DS_BaiBaoCao> tbl_HOINGHI_DS_BaiBaoCao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HOINGHI_DS_KhachMoi> tbl_HOINGHI_DS_KhachMoi { get; set; }
    }
}
