//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bankhcn_LienKet
    {
        public int Id { get; set; }
        public string TenPhongBan { get; set; }
        public string Link { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> orderCol { get; set; }
        public string coquan { get; set; }
    }
}
