//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DA_QuaTrinhThucHien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DA_QuaTrinhThucHien()
        {
            this.tbl_DA_BUOCTH_BaoCaoGiuaKy = new HashSet<tbl_DA_BUOCTH_BaoCaoGiuaKy>();
            this.tbl_DA_BUOCTH_BaoCaoTongKet = new HashSet<tbl_DA_BUOCTH_BaoCaoTongKet>();
            this.tbl_DA_BUOCTH_BienBan_ThanhLapHoiDong = new HashSet<tbl_DA_BUOCTH_BienBan_ThanhLapHoiDong>();
            this.tbl_DA_BUOCTH_BienBan2 = new HashSet<tbl_DA_BUOCTH_BienBan2>();
            this.tbl_DA_BUOCTH_DieuChinhKinhPhi = new HashSet<tbl_DA_BUOCTH_DieuChinhKinhPhi>();
            this.tbl_DA_BUOCTH_DieuChinhNoiDung = new HashSet<tbl_DA_BUOCTH_DieuChinhNoiDung>();
            this.tbl_DA_BUOCTH_GiaHan = new HashSet<tbl_DA_BUOCTH_GiaHan>();
            this.tbl_DA_BUOCTH_HopDong = new HashSet<tbl_DA_BUOCTH_HopDong>();
            this.tbl_DA_BUOCTH_KinhPhiDot1 = new HashSet<tbl_DA_BUOCTH_KinhPhiDot1>();
            this.tbl_DA_BUOCTH_KinhPhiDot2 = new HashSet<tbl_DA_BUOCTH_KinhPhiDot2>();
            this.tbl_DA_BUOCTH_KinhPhiDot3 = new HashSet<tbl_DA_BUOCTH_KinhPhiDot3>();
            this.tbl_DA_BUOCTH_NhanXet = new HashSet<tbl_DA_BUOCTH_NhanXet>();
            this.tbl_DA_BUOCTH_NhanXet2 = new HashSet<tbl_DA_BUOCTH_NhanXet2>();
            this.tbl_DA_BUOCTH_PhieuDangKyKetQua = new HashSet<tbl_DA_BUOCTH_PhieuDangKyKetQua>();
            this.tbl_DA_BUOCTH_PhieuDiem = new HashSet<tbl_DA_BUOCTH_PhieuDiem>();
            this.tbl_DA_BUOCTH_PhieuDiem2 = new HashSet<tbl_DA_BUOCTH_PhieuDiem2>();
            this.tbl_DA_BUOCTH_QuyetDinh = new HashSet<tbl_DA_BUOCTH_QuyetDinh>();
            this.tbl_DA_BUOCTH_QuyetDinhGiaoNhiemVu = new HashSet<tbl_DA_BUOCTH_QuyetDinhGiaoNhiemVu>();
            this.tbl_DA_BUOCTH_QuyetDinhHuy = new HashSet<tbl_DA_BUOCTH_QuyetDinhHuy>();
            this.tbl_DA_BUOCTH_QuyetDinhKiemTraGiuaKy = new HashSet<tbl_DA_BUOCTH_QuyetDinhKiemTraGiuaKy>();
            this.tbl_DA_BUOCTH_QuyetDinhNghiemThu = new HashSet<tbl_DA_BUOCTH_QuyetDinhNghiemThu>();
            this.tbl_DA_BUOCTH_QuyetDinhThanhLy = new HashSet<tbl_DA_BUOCTH_QuyetDinhThanhLy>();
            this.tbl_DA_BUOCTH_ThayChuNhiem = new HashSet<tbl_DA_BUOCTH_ThayChuNhiem>();
            this.tbl_DA_BUOCTH_ThuyetMinh = new HashSet<tbl_DA_BUOCTH_ThuyetMinh>();
            this.tbl_DA_KinhPhi_ChiTiet = new HashSet<tbl_DA_KinhPhi_ChiTiet>();
            this.tbl_DA_QuaTrinhThucHien_ChiTiet = new HashSet<tbl_DA_QuaTrinhThucHien_ChiTiet>();
            this.tbl_DA_QuaTrinhThucHien_File = new HashSet<tbl_DA_QuaTrinhThucHien_File>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MaDuAnId { get; set; }
        public Nullable<int> MaBuocId { get; set; }
        public string ThoiGianHoanThanh { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_BaoCaoGiuaKy> tbl_DA_BUOCTH_BaoCaoGiuaKy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_BaoCaoTongKet> tbl_DA_BUOCTH_BaoCaoTongKet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_BienBan_ThanhLapHoiDong> tbl_DA_BUOCTH_BienBan_ThanhLapHoiDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_BienBan2> tbl_DA_BUOCTH_BienBan2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_DieuChinhKinhPhi> tbl_DA_BUOCTH_DieuChinhKinhPhi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_DieuChinhNoiDung> tbl_DA_BUOCTH_DieuChinhNoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_GiaHan> tbl_DA_BUOCTH_GiaHan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_HopDong> tbl_DA_BUOCTH_HopDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_KinhPhiDot1> tbl_DA_BUOCTH_KinhPhiDot1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_KinhPhiDot2> tbl_DA_BUOCTH_KinhPhiDot2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_KinhPhiDot3> tbl_DA_BUOCTH_KinhPhiDot3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_NhanXet> tbl_DA_BUOCTH_NhanXet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_NhanXet2> tbl_DA_BUOCTH_NhanXet2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_PhieuDangKyKetQua> tbl_DA_BUOCTH_PhieuDangKyKetQua { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_PhieuDiem> tbl_DA_BUOCTH_PhieuDiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_PhieuDiem2> tbl_DA_BUOCTH_PhieuDiem2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_QuyetDinh> tbl_DA_BUOCTH_QuyetDinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_QuyetDinhGiaoNhiemVu> tbl_DA_BUOCTH_QuyetDinhGiaoNhiemVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_QuyetDinhHuy> tbl_DA_BUOCTH_QuyetDinhHuy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_QuyetDinhKiemTraGiuaKy> tbl_DA_BUOCTH_QuyetDinhKiemTraGiuaKy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_QuyetDinhNghiemThu> tbl_DA_BUOCTH_QuyetDinhNghiemThu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_QuyetDinhThanhLy> tbl_DA_BUOCTH_QuyetDinhThanhLy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_ThayChuNhiem> tbl_DA_BUOCTH_ThayChuNhiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_BUOCTH_ThuyetMinh> tbl_DA_BUOCTH_ThuyetMinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_KinhPhi_ChiTiet> tbl_DA_KinhPhi_ChiTiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_QuaTrinhThucHien_ChiTiet> tbl_DA_QuaTrinhThucHien_ChiTiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DA_QuaTrinhThucHien_File> tbl_DA_QuaTrinhThucHien_File { get; set; }
        public virtual tbl_DA_ThongTinChung tbl_DA_ThongTinChung { get; set; }
        public virtual tbl_DM_BuocThucHien_ChiTiet tbl_DM_BuocThucHien_ChiTiet { get; set; }
    }
}
