//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SHTT_Giaynhanxet_BangiamKhao
    {
        public int Id { get; set; }
        public Nullable<int> GiaynhanxetId { get; set; }
        public Nullable<int> CanboId { get; set; }
        public Nullable<double> Diemso { get; set; }
        public string NoidungNX { get; set; }
    
        public virtual tbl_HSCB_LyLichCanBo tbl_HSCB_LyLichCanBo { get; set; }
        public virtual tbl_SHTT_Giaynhanxet tbl_SHTT_Giaynhanxet { get; set; }
    }
}
