//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DT_HDN_NN
    {
        public int Id { get; set; }
        public int ProgrameId { get; set; }
        public int CanBoId { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TratTu { get; set; }
        public string NhiemKy { get; set; }
        public string ChucDanh { get; set; }
        public Nullable<int> ContentId { get; set; }
    
        public virtual tbl_DT_HDN_NN_Content tbl_DT_HDN_NN_Content { get; set; }
        public virtual tbl_HSCB_LyLichCanBo tbl_HSCB_LyLichCanBo { get; set; }
    }
}
