//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CJVINA_WorkingNote_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CJVINA_WorkingNote_Detail()
        {
            this.tbl_CJVINA_InFact = new HashSet<tbl_CJVINA_InFact>();
        }
    
        public int Id { get; set; }
        public Nullable<int> WorkingNoteId { get; set; }
        public Nullable<int> FormularId { get; set; }
    
        public virtual tbl_CJVINA_Formula tbl_CJVINA_Formula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CJVINA_InFact> tbl_CJVINA_InFact { get; set; }
        public virtual tbl_CJVINA_WorkingNote tbl_CJVINA_WorkingNote { get; set; }
    }
}
