//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GIAITHUONG_SV_DanhSachSVDangky
    {
        public int Id { get; set; }
        public Nullable<int> SinhvienId { get; set; }
        public Nullable<int> GiaithuongId { get; set; }
        public string NoidungChuDe { get; set; }
        public Nullable<double> ChamDiem { get; set; }
        public string FileDinhkem { get; set; }
        public Nullable<System.DateTime> NgayDangky { get; set; }
    }
}
