//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PTN_INFO_TrangThietBiPhu
    {
        public int Id { get; set; }
        public int PhongTNId { get; set; }
        public int ThietBiId { get; set; }
        public Nullable<int> QuocGiaId { get; set; }
        public string HangSanXuat { get; set; }
        public string ThoiGianMua { get; set; }
        public string ThoiGianDuaVaoSuDung { get; set; }
        public string CongDung { get; set; }
        public string ThongSoKyThuat { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<double> TriGia { get; set; }
        public Nullable<int> TanSuat { get; set; }
    
        public virtual tbl_DM_QuocGia tbl_DM_QuocGia { get; set; }
        public virtual tbl_DM_ThietBi tbl_DM_ThietBi { get; set; }
        public virtual tbl_PTN_INFO_ThongTinChung tbl_PTN_INFO_ThongTinChung { get; set; }
    }
}
