//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempHoang
    {
        public int Id { get; set; }
        public Nullable<int> ThuMucId { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<double> DeXuatDonVi { get; set; }
        public Nullable<double> UocTinhThucHien { get; set; }
        public Nullable<double> DuToanHieuChinh { get; set; }
        public string Ghichu { get; set; }
        public int MaThuMuc { get; set; }
        public string TenThuMuc { get; set; }
        public Nullable<int> ThuMucChaId { get; set; }
        public string GhiChuCha { get; set; }
    }
}
