//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_HoiDongNganh_NhomNganh
    {
        public int ProgrameId { get; set; }
        public int CanBoId { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Ten { get; set; }
        public string HH { get; set; }
        public string HV { get; set; }
        public string DVCT { get; set; }
        public string PB { get; set; }
        public Nullable<int> DVID { get; set; }
        public string NhiemKy { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TratTu { get; set; }
    }
}
