//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_QuaTrinh_QuyetDinhNghiemThu_NghiemThu
    {
        public int Id { get; set; }
        public Nullable<int> DuAnId { get; set; }
        public Nullable<int> MaBuocId { get; set; }
        public string ThoiGianHoanThanh { get; set; }
        public string GhiChu { get; set; }
        public string Ten { get; set; }
        public Nullable<int> QuaTrinhId { get; set; }
        public string File { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
    }
}
