//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_QuocSao
    {
        public int Id { get; set; }
        public string papertitle { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string DonVi { get; set; }
        public Nullable<int> programeid { get; set; }
        public string CT { get; set; }
        public Nullable<int> LinhVucId { get; set; }
        public string Ten { get; set; }
        public Nullable<int> Yearth { get; set; }
        public Nullable<int> AuthorId { get; set; }
    }
}
