//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_temp_0000001
    {
        public int Id { get; set; }
        public string Ten { get; set; }
        public string MaSo { get; set; }
        public Nullable<int> LoaiDuAnId { get; set; }
        public string LoaiDuAn { get; set; }
        public Nullable<int> ChuongTrinh { get; set; }
        public string TenCT { get; set; }
        public Nullable<int> LinhVuc { get; set; }
        public string TenLV { get; set; }
        public string TenCN { get; set; }
        public string NamBD { get; set; }
        public string NamKT { get; set; }
        public Nullable<double> KinhPhi { get; set; }
        public Nullable<int> CoQuanChuTri { get; set; }
        public Nullable<int> BuocId { get; set; }
        public string Code { get; set; }
        public string DKTK { get; set; }
    }
}
