//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Tho_CTNC_NNC
    {
        public int Id { get; set; }
        public string Ten { get; set; }
        public string LanhVucChinh { get; set; }
        public string tbl_PTN_INFO_ThongTinChung_PhongThiNghiemId_Name { get; set; }
        public string tbl_DM_TruongVien_MaTruongId_Ten { get; set; }
        public Nullable<int> CTNCId { get; set; }
        public string HocVi { get; set; }
        public string HocHam { get; set; }
    }
}
