//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ThucHien_BaoCaoGiuaKy
    {
        public int Id { get; set; }
        public int QuaTrinhId { get; set; }
        public string tbl_DA_QuaTrinhThucHien_QuaTrinhId_Id { get; set; }
        public string Ten { get; set; }
        public string HinhAnh_File { get; set; }
        public string NoiDung { get; set; }
        public string KetQua { get; set; }
        public string XepLoai { get; set; }
    }
}
