//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ThongTinChungNhaKhoaHoc
    {
        public string Mã_NKH { get; set; }
        public string Họ_tên { get; set; }
        public string Ngày_Sinh { get; set; }
        public string Giới_tính { get; set; }
        public string Đơn_vị_công_tác { get; set; }
        public string Khoa_Phòng { get; set; }
        public string Bộ_môn { get; set; }
        public string Phòng_thí_nghiệm { get; set; }
        public string Chức_vụ { get; set; }
        public string Học_hàm { get; set; }
        public string Năm_phong { get; set; }
        public string Học_vị { get; set; }
        public string Năm_đạt { get; set; }
        public string Địa_chỉ_CQ { get; set; }
        public string Điện_thoại_CQ { get; set; }
        public string Fax_CQ { get; set; }
        public string E_mail_CQ { get; set; }
        public string Địa_chỉ_CN { get; set; }
        public string Điện_thoại_CN { get; set; }
        public string E_mail_CN { get; set; }
        public string Website { get; set; }
        public string Ảnh_NKH { get; set; }
    }
}
